/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ActivityParticipantResponse } from "./ActivityParticipantResponse";
import {
  ActivityParticipantResponseFromJSON,
  ActivityParticipantResponseFromJSONTyped,
  ActivityParticipantResponseToJSON,
  ActivityParticipantResponseToJSONTyped,
} from "./ActivityParticipantResponse";

/**
 *
 * @export
 * @interface ActivitySessionResponse
 */
export interface ActivitySessionResponse {
  /**
   *
   * @type {string}
   * @memberof ActivitySessionResponse
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof ActivitySessionResponse
   */
  roomToken: string;
  /**
   *
   * @type {Date}
   * @memberof ActivitySessionResponse
   */
  roomTokenExpiresAt: Date;
  /**
   *
   * @type {string}
   * @memberof ActivitySessionResponse
   */
  instanceId: string;
  /**
   *
   * @type {ActivityParticipantResponse}
   * @memberof ActivitySessionResponse
   */
  participant: ActivityParticipantResponse;
}

/**
 * Check if a given object implements the ActivitySessionResponse interface.
 */
export function instanceOfActivitySessionResponse(
  value: object,
): value is ActivitySessionResponse {
  if (!("accessToken" in value) || value["accessToken"] === undefined)
    return false;
  if (!("roomToken" in value) || value["roomToken"] === undefined) return false;
  if (
    !("roomTokenExpiresAt" in value) ||
    value["roomTokenExpiresAt"] === undefined
  )
    return false;
  if (!("instanceId" in value) || value["instanceId"] === undefined)
    return false;
  if (!("participant" in value) || value["participant"] === undefined)
    return false;
  return true;
}

export function ActivitySessionResponseFromJSON(
  json: any,
): ActivitySessionResponse {
  return ActivitySessionResponseFromJSONTyped(json, false);
}

export function ActivitySessionResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActivitySessionResponse {
  if (json == null) {
    return json;
  }
  return {
    accessToken: json["access_token"],
    roomToken: json["room_token"],
    roomTokenExpiresAt: new Date(json["room_token_expires_at"]),
    instanceId: json["instance_id"],
    participant: ActivityParticipantResponseFromJSON(json["participant"]),
  };
}

export function ActivitySessionResponseToJSON(
  json: any,
): ActivitySessionResponse {
  return ActivitySessionResponseToJSONTyped(json, false);
}

export function ActivitySessionResponseToJSONTyped(
  value?: ActivitySessionResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    access_token: value["accessToken"],
    room_token: value["roomToken"],
    room_token_expires_at: value["roomTokenExpiresAt"].toISOString(),
    instance_id: value["instanceId"],
    participant: ActivityParticipantResponseToJSON(value["participant"]),
  };
}
