/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ActivityTokenRequest
 */
export interface ActivityTokenRequest {
  /**
   *
   * @type {string}
   * @memberof ActivityTokenRequest
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof ActivityTokenRequest
   */
  instanceId: string;
}

/**
 * Check if a given object implements the ActivityTokenRequest interface.
 */
export function instanceOfActivityTokenRequest(
  value: object,
): value is ActivityTokenRequest {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("instanceId" in value) || value["instanceId"] === undefined)
    return false;
  return true;
}

export function ActivityTokenRequestFromJSON(json: any): ActivityTokenRequest {
  return ActivityTokenRequestFromJSONTyped(json, false);
}

export function ActivityTokenRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActivityTokenRequest {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    instanceId: json["instance_id"],
  };
}

export function ActivityTokenRequestToJSON(json: any): ActivityTokenRequest {
  return ActivityTokenRequestToJSONTyped(json, false);
}

export function ActivityTokenRequestToJSONTyped(
  value?: ActivityTokenRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    instance_id: value["instanceId"],
  };
}
