/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ActivityClip } from "./ActivityClip";
import {
  ActivityClipFromJSON,
  ActivityClipFromJSONTyped,
  ActivityClipToJSON,
  ActivityClipToJSONTyped,
} from "./ActivityClip";

/**
 *
 * @export
 * @interface ActivityClipsResponse
 */
export interface ActivityClipsResponse {
  /**
   *
   * @type {Array<ActivityClip>}
   * @memberof ActivityClipsResponse
   */
  clips: Array<ActivityClip>;
  /**
   *
   * @type {boolean}
   * @memberof ActivityClipsResponse
   */
  hasMore: boolean;
}

/**
 * Check if a given object implements the ActivityClipsResponse interface.
 */
export function instanceOfActivityClipsResponse(
  value: object,
): value is ActivityClipsResponse {
  if (!("clips" in value) || value["clips"] === undefined) return false;
  if (!("hasMore" in value) || value["hasMore"] === undefined) return false;
  return true;
}

export function ActivityClipsResponseFromJSON(
  json: any,
): ActivityClipsResponse {
  return ActivityClipsResponseFromJSONTyped(json, false);
}

export function ActivityClipsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActivityClipsResponse {
  if (json == null) {
    return json;
  }
  return {
    clips: (json["clips"] as Array<any>).map(ActivityClipFromJSON),
    hasMore: json["has_more"],
  };
}

export function ActivityClipsResponseToJSON(json: any): ActivityClipsResponse {
  return ActivityClipsResponseToJSONTyped(json, false);
}

export function ActivityClipsResponseToJSONTyped(
  value?: ActivityClipsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clips: (value["clips"] as Array<any>).map(ActivityClipToJSON),
    has_more: value["hasMore"],
  };
}
