/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Clips | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AddCustomCategoryRequest
 */
export interface AddCustomCategoryRequest {
  /**
   *
   * @type {string}
   * @memberof AddCustomCategoryRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof AddCustomCategoryRequest
   */
  coverUrl: string | null;
}

/**
 * Check if a given object implements the AddCustomCategoryRequest interface.
 */
export function instanceOfAddCustomCategoryRequest(
  value: object,
): value is AddCustomCategoryRequest {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("coverUrl" in value) || value["coverUrl"] === undefined) return false;
  return true;
}

export function AddCustomCategoryRequestFromJSON(
  json: any,
): AddCustomCategoryRequest {
  return AddCustomCategoryRequestFromJSONTyped(json, false);
}

export function AddCustomCategoryRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddCustomCategoryRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    coverUrl: json["cover_url"],
  };
}

export function AddCustomCategoryRequestToJSON(
  json: any,
): AddCustomCategoryRequest {
  return AddCustomCategoryRequestToJSONTyped(json, false);
}

export function AddCustomCategoryRequestToJSONTyped(
  value?: AddCustomCategoryRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    cover_url: value["coverUrl"],
  };
}
