/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Clips | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AddClipToPlaylistRequest
 */
export interface AddClipToPlaylistRequest {
  /**
   *
   * @type {string}
   * @memberof AddClipToPlaylistRequest
   */
  clipId?: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof AddClipToPlaylistRequest
   */
  clipIds?: Array<string> | null;
}

/**
 * Check if a given object implements the AddClipToPlaylistRequest interface.
 */
export function instanceOfAddClipToPlaylistRequest(
  value: object,
): value is AddClipToPlaylistRequest {
  return true;
}

export function AddClipToPlaylistRequestFromJSON(
  json: any,
): AddClipToPlaylistRequest {
  return AddClipToPlaylistRequestFromJSONTyped(json, false);
}

export function AddClipToPlaylistRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddClipToPlaylistRequest {
  if (json == null) {
    return json;
  }
  return {
    clipId: json["clip_id"] == null ? undefined : json["clip_id"],
    clipIds: json["clip_ids"] == null ? undefined : json["clip_ids"],
  };
}

export function AddClipToPlaylistRequestToJSON(
  json: any,
): AddClipToPlaylistRequest {
  return AddClipToPlaylistRequestToJSONTyped(json, false);
}

export function AddClipToPlaylistRequestToJSONTyped(
  value?: AddClipToPlaylistRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clip_id: value["clipId"],
    clip_ids: value["clipIds"],
  };
}
