/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AddGameFromIgdbRequest
 */
export interface AddGameFromIgdbRequest {
  /**
   *
   * @type {number}
   * @memberof AddGameFromIgdbRequest
   */
  igdbId: number;
}

/**
 * Check if a given object implements the AddGameFromIgdbRequest interface.
 */
export function instanceOfAddGameFromIgdbRequest(
  value: object,
): value is AddGameFromIgdbRequest {
  if (!("igdbId" in value) || value["igdbId"] === undefined) return false;
  return true;
}

export function AddGameFromIgdbRequestFromJSON(
  json: any,
): AddGameFromIgdbRequest {
  return AddGameFromIgdbRequestFromJSONTyped(json, false);
}

export function AddGameFromIgdbRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddGameFromIgdbRequest {
  if (json == null) {
    return json;
  }
  return {
    igdbId: json["igdb_id"],
  };
}

export function AddGameFromIgdbRequestToJSON(
  json: any,
): AddGameFromIgdbRequest {
  return AddGameFromIgdbRequestToJSONTyped(json, false);
}

export function AddGameFromIgdbRequestToJSONTyped(
  value?: AddGameFromIgdbRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    igdb_id: value["igdbId"],
  };
}
