/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BackfillClipSummaryRequest
 */
export interface BackfillClipSummaryRequest {
  /**
   *
   * @type {string}
   * @memberof BackfillClipSummaryRequest
   */
  reasoningEffort: string | null;
}

/**
 * Check if a given object implements the BackfillClipSummaryRequest interface.
 */
export function instanceOfBackfillClipSummaryRequest(
  value: object,
): value is BackfillClipSummaryRequest {
  if (!("reasoningEffort" in value) || value["reasoningEffort"] === undefined)
    return false;
  return true;
}

export function BackfillClipSummaryRequestFromJSON(
  json: any,
): BackfillClipSummaryRequest {
  return BackfillClipSummaryRequestFromJSONTyped(json, false);
}

export function BackfillClipSummaryRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BackfillClipSummaryRequest {
  if (json == null) {
    return json;
  }
  return {
    reasoningEffort: json["reasoning_effort"],
  };
}

export function BackfillClipSummaryRequestToJSON(
  json: any,
): BackfillClipSummaryRequest {
  return BackfillClipSummaryRequestToJSONTyped(json, false);
}

export function BackfillClipSummaryRequestToJSONTyped(
  value?: BackfillClipSummaryRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    reasoning_effort: value["reasoningEffort"],
  };
}
