/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ClipSummaryRun
 */
export interface ClipSummaryRun {
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  clipId: string;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  sourceTranscriptionRunId: string;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  trigger: string;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  provider: string;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  model: string;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  reasoningEffort: string | null;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  promptVersion: string | null;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  status: string;
  /**
   *
   * @type {number}
   * @memberof ClipSummaryRun
   */
  attempts: number;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  description: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof ClipSummaryRun
   */
  moodTags: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof ClipSummaryRun
   */
  quotes: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof ClipSummaryRun
   */
  people: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof ClipSummaryRun
   */
  hasEmbedding: boolean;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  embeddingModel: string;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  rawResponse: string | null;
  /**
   *
   * @type {number}
   * @memberof ClipSummaryRun
   */
  inputTokens: number | null;
  /**
   *
   * @type {number}
   * @memberof ClipSummaryRun
   */
  cachedInputTokens: number | null;
  /**
   *
   * @type {number}
   * @memberof ClipSummaryRun
   */
  outputTokens: number | null;
  /**
   *
   * @type {number}
   * @memberof ClipSummaryRun
   */
  embeddingTokens: number | null;
  /**
   *
   * @type {number}
   * @memberof ClipSummaryRun
   */
  durationMs: number | null;
  /**
   *
   * @type {string}
   * @memberof ClipSummaryRun
   */
  error: string | null;
  /**
   *
   * @type {Date}
   * @memberof ClipSummaryRun
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof ClipSummaryRun
   */
  completedAt: Date | null;
}

/**
 * Check if a given object implements the ClipSummaryRun interface.
 */
export function instanceOfClipSummaryRun(
  value: object,
): value is ClipSummaryRun {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("clipId" in value) || value["clipId"] === undefined) return false;
  if (
    !("sourceTranscriptionRunId" in value) ||
    value["sourceTranscriptionRunId"] === undefined
  )
    return false;
  if (!("trigger" in value) || value["trigger"] === undefined) return false;
  if (!("provider" in value) || value["provider"] === undefined) return false;
  if (!("model" in value) || value["model"] === undefined) return false;
  if (!("reasoningEffort" in value) || value["reasoningEffort"] === undefined)
    return false;
  if (!("promptVersion" in value) || value["promptVersion"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("attempts" in value) || value["attempts"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("moodTags" in value) || value["moodTags"] === undefined) return false;
  if (!("quotes" in value) || value["quotes"] === undefined) return false;
  if (!("people" in value) || value["people"] === undefined) return false;
  if (!("hasEmbedding" in value) || value["hasEmbedding"] === undefined)
    return false;
  if (!("embeddingModel" in value) || value["embeddingModel"] === undefined)
    return false;
  if (!("rawResponse" in value) || value["rawResponse"] === undefined)
    return false;
  if (!("inputTokens" in value) || value["inputTokens"] === undefined)
    return false;
  if (
    !("cachedInputTokens" in value) ||
    value["cachedInputTokens"] === undefined
  )
    return false;
  if (!("outputTokens" in value) || value["outputTokens"] === undefined)
    return false;
  if (!("embeddingTokens" in value) || value["embeddingTokens"] === undefined)
    return false;
  if (!("durationMs" in value) || value["durationMs"] === undefined)
    return false;
  if (!("error" in value) || value["error"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("completedAt" in value) || value["completedAt"] === undefined)
    return false;
  return true;
}

export function ClipSummaryRunFromJSON(json: any): ClipSummaryRun {
  return ClipSummaryRunFromJSONTyped(json, false);
}

export function ClipSummaryRunFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClipSummaryRun {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    clipId: json["clip_id"],
    sourceTranscriptionRunId: json["source_transcription_run_id"],
    trigger: json["trigger"],
    provider: json["provider"],
    model: json["model"],
    reasoningEffort: json["reasoning_effort"],
    promptVersion: json["prompt_version"],
    status: json["status"],
    attempts: json["attempts"],
    description: json["description"],
    moodTags: json["mood_tags"],
    quotes: json["quotes"],
    people: json["people"],
    hasEmbedding: json["has_embedding"],
    embeddingModel: json["embedding_model"],
    rawResponse: json["raw_response"],
    inputTokens: json["input_tokens"],
    cachedInputTokens: json["cached_input_tokens"],
    outputTokens: json["output_tokens"],
    embeddingTokens: json["embedding_tokens"],
    durationMs: json["duration_ms"],
    error: json["error"],
    createdAt: new Date(json["created_at"]),
    completedAt:
      json["completed_at"] == null ? null : new Date(json["completed_at"]),
  };
}

export function ClipSummaryRunToJSON(json: any): ClipSummaryRun {
  return ClipSummaryRunToJSONTyped(json, false);
}

export function ClipSummaryRunToJSONTyped(
  value?: ClipSummaryRun | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    clip_id: value["clipId"],
    source_transcription_run_id: value["sourceTranscriptionRunId"],
    trigger: value["trigger"],
    provider: value["provider"],
    model: value["model"],
    reasoning_effort: value["reasoningEffort"],
    prompt_version: value["promptVersion"],
    status: value["status"],
    attempts: value["attempts"],
    description: value["description"],
    mood_tags: value["moodTags"],
    quotes: value["quotes"],
    people: value["people"],
    has_embedding: value["hasEmbedding"],
    embedding_model: value["embeddingModel"],
    raw_response: value["rawResponse"],
    input_tokens: value["inputTokens"],
    cached_input_tokens: value["cachedInputTokens"],
    output_tokens: value["outputTokens"],
    embedding_tokens: value["embeddingTokens"],
    duration_ms: value["durationMs"],
    error: value["error"],
    created_at: value["createdAt"].toISOString(),
    completed_at:
      value["completedAt"] == null
        ? value["completedAt"]
        : value["completedAt"].toISOString(),
  };
}
