/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Clip } from "./Clip";
import {
  ClipFromJSON,
  ClipFromJSONTyped,
  ClipToJSON,
  ClipToJSONTyped,
} from "./Clip";
import type { GameCategoryResponse } from "./GameCategoryResponse";
import {
  GameCategoryResponseFromJSON,
  GameCategoryResponseFromJSONTyped,
  GameCategoryResponseToJSON,
  GameCategoryResponseToJSONTyped,
} from "./GameCategoryResponse";

/**
 *
 * @export
 * @interface ClipLibraryResponse
 */
export interface ClipLibraryResponse {
  /**
   *
   * @type {Array<GameCategoryResponse>}
   * @memberof ClipLibraryResponse
   */
  categories: Array<GameCategoryResponse>;
  /**
   *
   * @type {Array<Clip>}
   * @memberof ClipLibraryResponse
   */
  clips: Array<Clip>;
}

/**
 * Check if a given object implements the ClipLibraryResponse interface.
 */
export function instanceOfClipLibraryResponse(
  value: object,
): value is ClipLibraryResponse {
  if (!("categories" in value) || value["categories"] === undefined)
    return false;
  if (!("clips" in value) || value["clips"] === undefined) return false;
  return true;
}

export function ClipLibraryResponseFromJSON(json: any): ClipLibraryResponse {
  return ClipLibraryResponseFromJSONTyped(json, false);
}

export function ClipLibraryResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClipLibraryResponse {
  if (json == null) {
    return json;
  }
  return {
    categories: (json["categories"] as Array<any>).map(
      GameCategoryResponseFromJSON,
    ),
    clips: (json["clips"] as Array<any>).map(ClipFromJSON),
  };
}

export function ClipLibraryResponseToJSON(json: any): ClipLibraryResponse {
  return ClipLibraryResponseToJSONTyped(json, false);
}

export function ClipLibraryResponseToJSONTyped(
  value?: ClipLibraryResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    categories: (value["categories"] as Array<any>).map(
      GameCategoryResponseToJSON,
    ),
    clips: (value["clips"] as Array<any>).map(ClipToJSON),
  };
}
