/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ClipSummaryBackfillResponse
 */
export interface ClipSummaryBackfillResponse {
  /**
   *
   * @type {number}
   * @memberof ClipSummaryBackfillResponse
   */
  queued: number;
}

/**
 * Check if a given object implements the ClipSummaryBackfillResponse interface.
 */
export function instanceOfClipSummaryBackfillResponse(
  value: object,
): value is ClipSummaryBackfillResponse {
  if (!("queued" in value) || value["queued"] === undefined) return false;
  return true;
}

export function ClipSummaryBackfillResponseFromJSON(
  json: any,
): ClipSummaryBackfillResponse {
  return ClipSummaryBackfillResponseFromJSONTyped(json, false);
}

export function ClipSummaryBackfillResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClipSummaryBackfillResponse {
  if (json == null) {
    return json;
  }
  return {
    queued: json["queued"],
  };
}

export function ClipSummaryBackfillResponseToJSON(
  json: any,
): ClipSummaryBackfillResponse {
  return ClipSummaryBackfillResponseToJSONTyped(json, false);
}

export function ClipSummaryBackfillResponseToJSONTyped(
  value?: ClipSummaryBackfillResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    queued: value["queued"],
  };
}
