/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BunnyVideo } from "./BunnyVideo";
import {
  BunnyVideoFromJSON,
  BunnyVideoFromJSONTyped,
  BunnyVideoToJSON,
  BunnyVideoToJSONTyped,
} from "./BunnyVideo";
import type { ClipShareSummary } from "./ClipShareSummary";
import {
  ClipShareSummaryFromJSON,
  ClipShareSummaryFromJSONTyped,
  ClipShareSummaryToJSON,
  ClipShareSummaryToJSONTyped,
} from "./ClipShareSummary";

/**
 *
 * @export
 * @interface Clip
 */
export interface Clip {
  /**
   *
   * @type {string}
   * @memberof Clip
   */
  clipId: string;
  /**
   *
   * @type {string}
   * @memberof Clip
   */
  ownerId: string;
  /**
   *
   * @type {string}
   * @memberof Clip
   */
  videoId: string;
  /**
   *
   * @type {string}
   * @memberof Clip
   */
  gameCategoryId: string;
  /**
   *
   * @type {string}
   * @memberof Clip
   */
  categorySlug: string;
  /**
   *
   * @type {Date}
   * @memberof Clip
   */
  createdAt: Date;
  /**
   *
   * @type {BunnyVideo}
   * @memberof Clip
   */
  video: BunnyVideo;
  /**
   *
   * @type {Array<string>}
   * @memberof Clip
   */
  tags: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof Clip
   */
  isViewed: boolean;
  /**
   *
   * @type {ClipShareSummary}
   * @memberof Clip
   */
  share: ClipShareSummary;
  /**
   *
   * @type {any}
   * @memberof Clip
   */
  gameMetadata: any | null;
}

/**
 * Check if a given object implements the Clip interface.
 */
export function instanceOfClip(value: object): value is Clip {
  if (!("clipId" in value) || value["clipId"] === undefined) return false;
  if (!("ownerId" in value) || value["ownerId"] === undefined) return false;
  if (!("videoId" in value) || value["videoId"] === undefined) return false;
  if (!("gameCategoryId" in value) || value["gameCategoryId"] === undefined)
    return false;
  if (!("categorySlug" in value) || value["categorySlug"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("video" in value) || value["video"] === undefined) return false;
  if (!("tags" in value) || value["tags"] === undefined) return false;
  if (!("isViewed" in value) || value["isViewed"] === undefined) return false;
  if (!("share" in value) || value["share"] === undefined) return false;
  if (!("gameMetadata" in value) || value["gameMetadata"] === undefined)
    return false;
  return true;
}

export function ClipFromJSON(json: any): Clip {
  return ClipFromJSONTyped(json, false);
}

export function ClipFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Clip {
  if (json == null) {
    return json;
  }
  return {
    clipId: json["clip_id"],
    ownerId: json["owner_id"],
    videoId: json["video_id"],
    gameCategoryId: json["game_category_id"],
    categorySlug: json["category_slug"],
    createdAt: new Date(json["created_at"]),
    video: BunnyVideoFromJSON(json["video"]),
    tags: json["tags"],
    isViewed: json["is_viewed"],
    share: ClipShareSummaryFromJSON(json["share"]),
    gameMetadata: json["game_metadata"],
  };
}

export function ClipToJSON(json: any): Clip {
  return ClipToJSONTyped(json, false);
}

export function ClipToJSONTyped(
  value?: Clip | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clip_id: value["clipId"],
    owner_id: value["ownerId"],
    video_id: value["videoId"],
    game_category_id: value["gameCategoryId"],
    category_slug: value["categorySlug"],
    created_at: value["createdAt"].toISOString(),
    video: BunnyVideoToJSON(value["video"]),
    tags: value["tags"],
    is_viewed: value["isViewed"],
    share: ClipShareSummaryToJSON(value["share"]),
    game_metadata: value["gameMetadata"],
  };
}
