/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ClipShareSummary
 */
export interface ClipShareSummary {
  /**
   *
   * @type {boolean}
   * @memberof ClipShareSummary
   */
  shared: boolean;
}

/**
 * Check if a given object implements the ClipShareSummary interface.
 */
export function instanceOfClipShareSummary(
  value: object,
): value is ClipShareSummary {
  if (!("shared" in value) || value["shared"] === undefined) return false;
  return true;
}

export function ClipShareSummaryFromJSON(json: any): ClipShareSummary {
  return ClipShareSummaryFromJSONTyped(json, false);
}

export function ClipShareSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClipShareSummary {
  if (json == null) {
    return json;
  }
  return {
    shared: json["shared"],
  };
}

export function ClipShareSummaryToJSON(json: any): ClipShareSummary {
  return ClipShareSummaryToJSONTyped(json, false);
}

export function ClipShareSummaryToJSONTyped(
  value?: ClipShareSummary | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    shared: value["shared"],
  };
}
