/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ClipTranscriptionBackfillResponse
 */
export interface ClipTranscriptionBackfillResponse {
  /**
   *
   * @type {number}
   * @memberof ClipTranscriptionBackfillResponse
   */
  queued: number;
}

/**
 * Check if a given object implements the ClipTranscriptionBackfillResponse interface.
 */
export function instanceOfClipTranscriptionBackfillResponse(
  value: object,
): value is ClipTranscriptionBackfillResponse {
  if (!("queued" in value) || value["queued"] === undefined) return false;
  return true;
}

export function ClipTranscriptionBackfillResponseFromJSON(
  json: any,
): ClipTranscriptionBackfillResponse {
  return ClipTranscriptionBackfillResponseFromJSONTyped(json, false);
}

export function ClipTranscriptionBackfillResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClipTranscriptionBackfillResponse {
  if (json == null) {
    return json;
  }
  return {
    queued: json["queued"],
  };
}

export function ClipTranscriptionBackfillResponseToJSON(
  json: any,
): ClipTranscriptionBackfillResponse {
  return ClipTranscriptionBackfillResponseToJSONTyped(json, false);
}

export function ClipTranscriptionBackfillResponseToJSONTyped(
  value?: ClipTranscriptionBackfillResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    queued: value["queued"],
  };
}
