/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ClipLibraryTotals
 */
export interface ClipLibraryTotals {
  /**
   *
   * @type {number}
   * @memberof ClipLibraryTotals
   */
  clipCount: number;
  /**
   *
   * @type {number}
   * @memberof ClipLibraryTotals
   */
  durationSeconds: number;
  /**
   *
   * @type {number}
   * @memberof ClipLibraryTotals
   */
  storageBytes: number;
}

/**
 * Check if a given object implements the ClipLibraryTotals interface.
 */
export function instanceOfClipLibraryTotals(
  value: object,
): value is ClipLibraryTotals {
  if (!("clipCount" in value) || value["clipCount"] === undefined) return false;
  if (!("durationSeconds" in value) || value["durationSeconds"] === undefined)
    return false;
  if (!("storageBytes" in value) || value["storageBytes"] === undefined)
    return false;
  return true;
}

export function ClipLibraryTotalsFromJSON(json: any): ClipLibraryTotals {
  return ClipLibraryTotalsFromJSONTyped(json, false);
}

export function ClipLibraryTotalsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClipLibraryTotals {
  if (json == null) {
    return json;
  }
  return {
    clipCount: json["clip_count"],
    durationSeconds: json["duration_seconds"],
    storageBytes: json["storage_bytes"],
  };
}

export function ClipLibraryTotalsToJSON(json: any): ClipLibraryTotals {
  return ClipLibraryTotalsToJSONTyped(json, false);
}

export function ClipLibraryTotalsToJSONTyped(
  value?: ClipLibraryTotals | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clip_count: value["clipCount"],
    duration_seconds: value["durationSeconds"],
    storage_bytes: value["storageBytes"],
  };
}
