/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ClipCategoryTotals
 */
export interface ClipCategoryTotals {
  /**
   *
   * @type {string}
   * @memberof ClipCategoryTotals
   */
  gameCategoryId: string;
  /**
   *
   * @type {number}
   * @memberof ClipCategoryTotals
   */
  clipCount: number;
  /**
   *
   * @type {number}
   * @memberof ClipCategoryTotals
   */
  durationSeconds: number;
  /**
   *
   * @type {number}
   * @memberof ClipCategoryTotals
   */
  storageBytes: number;
}

/**
 * Check if a given object implements the ClipCategoryTotals interface.
 */
export function instanceOfClipCategoryTotals(
  value: object,
): value is ClipCategoryTotals {
  if (!("gameCategoryId" in value) || value["gameCategoryId"] === undefined)
    return false;
  if (!("clipCount" in value) || value["clipCount"] === undefined) return false;
  if (!("durationSeconds" in value) || value["durationSeconds"] === undefined)
    return false;
  if (!("storageBytes" in value) || value["storageBytes"] === undefined)
    return false;
  return true;
}

export function ClipCategoryTotalsFromJSON(json: any): ClipCategoryTotals {
  return ClipCategoryTotalsFromJSONTyped(json, false);
}

export function ClipCategoryTotalsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClipCategoryTotals {
  if (json == null) {
    return json;
  }
  return {
    gameCategoryId: json["game_category_id"],
    clipCount: json["clip_count"],
    durationSeconds: json["duration_seconds"],
    storageBytes: json["storage_bytes"],
  };
}

export function ClipCategoryTotalsToJSON(json: any): ClipCategoryTotals {
  return ClipCategoryTotalsToJSONTyped(json, false);
}

export function ClipCategoryTotalsToJSONTyped(
  value?: ClipCategoryTotals | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    game_category_id: value["gameCategoryId"],
    clip_count: value["clipCount"],
    duration_seconds: value["durationSeconds"],
    storage_bytes: value["storageBytes"],
  };
}
