/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DeleteAccountRequest
 */
export interface DeleteAccountRequest {
  /**
   *
   * @type {string}
   * @memberof DeleteAccountRequest
   */
  confirmation: string | null;
}

/**
 * Check if a given object implements the DeleteAccountRequest interface.
 */
export function instanceOfDeleteAccountRequest(
  value: object,
): value is DeleteAccountRequest {
  if (!("confirmation" in value) || value["confirmation"] === undefined)
    return false;
  return true;
}

export function DeleteAccountRequestFromJSON(json: any): DeleteAccountRequest {
  return DeleteAccountRequestFromJSONTyped(json, false);
}

export function DeleteAccountRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteAccountRequest {
  if (json == null) {
    return json;
  }
  return {
    confirmation: json["confirmation"],
  };
}

export function DeleteAccountRequestToJSON(json: any): DeleteAccountRequest {
  return DeleteAccountRequestToJSONTyped(json, false);
}

export function DeleteAccountRequestToJSONTyped(
  value?: DeleteAccountRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    confirmation: value["confirmation"],
  };
}
