/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DetectedTeammate
 */
export interface DetectedTeammate {
  /**
   *
   * @type {number}
   * @memberof DetectedTeammate
   */
  slot: number;
  /**
   *
   * @type {string}
   * @memberof DetectedTeammate
   */
  name: string | null;
  /**
   *
   * @type {string}
   * @memberof DetectedTeammate
   */
  legend: string | null;
  /**
   *
   * @type {number}
   * @memberof DetectedTeammate
   */
  nameConfidence: number;
  /**
   *
   * @type {number}
   * @memberof DetectedTeammate
   */
  legendConfidence: number;
}

/**
 * Check if a given object implements the DetectedTeammate interface.
 */
export function instanceOfDetectedTeammate(
  value: object,
): value is DetectedTeammate {
  if (!("slot" in value) || value["slot"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("legend" in value) || value["legend"] === undefined) return false;
  if (!("nameConfidence" in value) || value["nameConfidence"] === undefined)
    return false;
  if (!("legendConfidence" in value) || value["legendConfidence"] === undefined)
    return false;
  return true;
}

export function DetectedTeammateFromJSON(json: any): DetectedTeammate {
  return DetectedTeammateFromJSONTyped(json, false);
}

export function DetectedTeammateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DetectedTeammate {
  if (json == null) {
    return json;
  }
  return {
    slot: json["slot"],
    name: json["name"],
    legend: json["legend"],
    nameConfidence: json["name_confidence"],
    legendConfidence: json["legend_confidence"],
  };
}

export function DetectedTeammateToJSON(json: any): DetectedTeammate {
  return DetectedTeammateToJSONTyped(json, false);
}

export function DetectedTeammateToJSONTyped(
  value?: DetectedTeammate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    slot: value["slot"],
    name: value["name"],
    legend: value["legend"],
    name_confidence: value["nameConfidence"],
    legend_confidence: value["legendConfidence"],
  };
}
