/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EnsureGamingSessionPlaylistRequest
 */
export interface EnsureGamingSessionPlaylistRequest {
  /**
   *
   * @type {string}
   * @memberof EnsureGamingSessionPlaylistRequest
   */
  categoryId: string;
  /**
   *
   * @type {Date}
   * @memberof EnsureGamingSessionPlaylistRequest
   */
  sessionDate: Date;
  /**
   *
   * @type {Array<string>}
   * @memberof EnsureGamingSessionPlaylistRequest
   */
  clipIds: Array<string>;
  /**
   *
   * @type {string}
   * @memberof EnsureGamingSessionPlaylistRequest
   */
  timezone: string;
}

/**
 * Check if a given object implements the EnsureGamingSessionPlaylistRequest interface.
 */
export function instanceOfEnsureGamingSessionPlaylistRequest(
  value: object,
): value is EnsureGamingSessionPlaylistRequest {
  if (!("categoryId" in value) || value["categoryId"] === undefined)
    return false;
  if (!("sessionDate" in value) || value["sessionDate"] === undefined)
    return false;
  if (!("clipIds" in value) || value["clipIds"] === undefined) return false;
  if (!("timezone" in value) || value["timezone"] === undefined) return false;
  return true;
}

export function EnsureGamingSessionPlaylistRequestFromJSON(
  json: any,
): EnsureGamingSessionPlaylistRequest {
  return EnsureGamingSessionPlaylistRequestFromJSONTyped(json, false);
}

export function EnsureGamingSessionPlaylistRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EnsureGamingSessionPlaylistRequest {
  if (json == null) {
    return json;
  }
  return {
    categoryId: json["category_id"],
    sessionDate: new Date(json["session_date"]),
    clipIds: json["clip_ids"],
    timezone: json["timezone"],
  };
}

export function EnsureGamingSessionPlaylistRequestToJSON(
  json: any,
): EnsureGamingSessionPlaylistRequest {
  return EnsureGamingSessionPlaylistRequestToJSONTyped(json, false);
}

export function EnsureGamingSessionPlaylistRequestToJSONTyped(
  value?: EnsureGamingSessionPlaylistRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    category_id: value["categoryId"],
    session_date: value["sessionDate"].toISOString().substring(0, 10),
    clip_ids: value["clipIds"],
    timezone: value["timezone"],
  };
}
