/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ImportedTwitchClipResponse
 */
export interface ImportedTwitchClipResponse {
  /**
   *
   * @type {string}
   * @memberof ImportedTwitchClipResponse
   */
  clipId: string;
  /**
   *
   * @type {string}
   * @memberof ImportedTwitchClipResponse
   */
  videoId: string;
  /**
   *
   * @type {string}
   * @memberof ImportedTwitchClipResponse
   */
  twitchClipId: string;
  /**
   *
   * @type {string}
   * @memberof ImportedTwitchClipResponse
   */
  categoryId: string;
  /**
   *
   * @type {Date}
   * @memberof ImportedTwitchClipResponse
   */
  createdAt: Date;
}

/**
 * Check if a given object implements the ImportedTwitchClipResponse interface.
 */
export function instanceOfImportedTwitchClipResponse(
  value: object,
): value is ImportedTwitchClipResponse {
  if (!("clipId" in value) || value["clipId"] === undefined) return false;
  if (!("videoId" in value) || value["videoId"] === undefined) return false;
  if (!("twitchClipId" in value) || value["twitchClipId"] === undefined)
    return false;
  if (!("categoryId" in value) || value["categoryId"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  return true;
}

export function ImportedTwitchClipResponseFromJSON(
  json: any,
): ImportedTwitchClipResponse {
  return ImportedTwitchClipResponseFromJSONTyped(json, false);
}

export function ImportedTwitchClipResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ImportedTwitchClipResponse {
  if (json == null) {
    return json;
  }
  return {
    clipId: json["clip_id"],
    videoId: json["video_id"],
    twitchClipId: json["twitch_clip_id"],
    categoryId: json["category_id"],
    createdAt: new Date(json["created_at"]),
  };
}

export function ImportedTwitchClipResponseToJSON(
  json: any,
): ImportedTwitchClipResponse {
  return ImportedTwitchClipResponseToJSONTyped(json, false);
}

export function ImportedTwitchClipResponseToJSONTyped(
  value?: ImportedTwitchClipResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clip_id: value["clipId"],
    video_id: value["videoId"],
    twitch_clip_id: value["twitchClipId"],
    category_id: value["categoryId"],
    created_at: value["createdAt"].toISOString(),
  };
}
