/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LegendDetectionArchiveResponse
 */
export interface LegendDetectionArchiveResponse {
  /**
   *
   * @type {number}
   * @memberof LegendDetectionArchiveResponse
   */
  archived: number;
}

/**
 * Check if a given object implements the LegendDetectionArchiveResponse interface.
 */
export function instanceOfLegendDetectionArchiveResponse(
  value: object,
): value is LegendDetectionArchiveResponse {
  if (!("archived" in value) || value["archived"] === undefined) return false;
  return true;
}

export function LegendDetectionArchiveResponseFromJSON(
  json: any,
): LegendDetectionArchiveResponse {
  return LegendDetectionArchiveResponseFromJSONTyped(json, false);
}

export function LegendDetectionArchiveResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LegendDetectionArchiveResponse {
  if (json == null) {
    return json;
  }
  return {
    archived: json["archived"],
  };
}

export function LegendDetectionArchiveResponseToJSON(
  json: any,
): LegendDetectionArchiveResponse {
  return LegendDetectionArchiveResponseToJSONTyped(json, false);
}

export function LegendDetectionArchiveResponseToJSONTyped(
  value?: LegendDetectionArchiveResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    archived: value["archived"],
  };
}
