/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { LegendDetectionRun } from "./LegendDetectionRun";
import {
  LegendDetectionRunFromJSON,
  LegendDetectionRunFromJSONTyped,
  LegendDetectionRunToJSON,
  LegendDetectionRunToJSONTyped,
} from "./LegendDetectionRun";
import type { LegendDetectionLabel } from "./LegendDetectionLabel";
import {
  LegendDetectionLabelFromJSON,
  LegendDetectionLabelFromJSONTyped,
  LegendDetectionLabelToJSON,
  LegendDetectionLabelToJSONTyped,
} from "./LegendDetectionLabel";

/**
 *
 * @export
 * @interface LegendDetectionReviewClip
 */
export interface LegendDetectionReviewClip {
  /**
   *
   * @type {string}
   * @memberof LegendDetectionReviewClip
   */
  clipId: string;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionReviewClip
   */
  title: string;
  /**
   *
   * @type {Date}
   * @memberof LegendDetectionReviewClip
   */
  createdAt: Date;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionReviewClip
   */
  lengthSeconds: number | null;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionReviewClip
   */
  embedUrl: string;
  /**
   *
   * @type {Array<string>}
   * @memberof LegendDetectionReviewClip
   */
  frameUrls: Array<string>;
  /**
   *
   * @type {LegendDetectionRun}
   * @memberof LegendDetectionReviewClip
   */
  latestRun: LegendDetectionRun | null;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionReviewClip
   */
  runCount: number;
  /**
   *
   * @type {LegendDetectionLabel}
   * @memberof LegendDetectionReviewClip
   */
  label: LegendDetectionLabel | null;
}

/**
 * Check if a given object implements the LegendDetectionReviewClip interface.
 */
export function instanceOfLegendDetectionReviewClip(
  value: object,
): value is LegendDetectionReviewClip {
  if (!("clipId" in value) || value["clipId"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("lengthSeconds" in value) || value["lengthSeconds"] === undefined)
    return false;
  if (!("embedUrl" in value) || value["embedUrl"] === undefined) return false;
  if (!("frameUrls" in value) || value["frameUrls"] === undefined) return false;
  if (!("latestRun" in value) || value["latestRun"] === undefined) return false;
  if (!("runCount" in value) || value["runCount"] === undefined) return false;
  if (!("label" in value) || value["label"] === undefined) return false;
  return true;
}

export function LegendDetectionReviewClipFromJSON(
  json: any,
): LegendDetectionReviewClip {
  return LegendDetectionReviewClipFromJSONTyped(json, false);
}

export function LegendDetectionReviewClipFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LegendDetectionReviewClip {
  if (json == null) {
    return json;
  }
  return {
    clipId: json["clip_id"],
    title: json["title"],
    createdAt: new Date(json["created_at"]),
    lengthSeconds: json["length_seconds"],
    embedUrl: json["embed_url"],
    frameUrls: json["frame_urls"],
    latestRun: LegendDetectionRunFromJSON(json["latest_run"]),
    runCount: json["run_count"],
    label: LegendDetectionLabelFromJSON(json["label"]),
  };
}

export function LegendDetectionReviewClipToJSON(
  json: any,
): LegendDetectionReviewClip {
  return LegendDetectionReviewClipToJSONTyped(json, false);
}

export function LegendDetectionReviewClipToJSONTyped(
  value?: LegendDetectionReviewClip | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clip_id: value["clipId"],
    title: value["title"],
    created_at: value["createdAt"].toISOString(),
    length_seconds: value["lengthSeconds"],
    embed_url: value["embedUrl"],
    frame_urls: value["frameUrls"],
    latest_run: LegendDetectionRunToJSON(value["latestRun"]),
    run_count: value["runCount"],
    label: LegendDetectionLabelToJSON(value["label"]),
  };
}
