/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LegendDetectionQueuedRunsResponse
 */
export interface LegendDetectionQueuedRunsResponse {
  /**
   *
   * @type {number}
   * @memberof LegendDetectionQueuedRunsResponse
   */
  queued: number;
}

/**
 * Check if a given object implements the LegendDetectionQueuedRunsResponse interface.
 */
export function instanceOfLegendDetectionQueuedRunsResponse(
  value: object,
): value is LegendDetectionQueuedRunsResponse {
  if (!("queued" in value) || value["queued"] === undefined) return false;
  return true;
}

export function LegendDetectionQueuedRunsResponseFromJSON(
  json: any,
): LegendDetectionQueuedRunsResponse {
  return LegendDetectionQueuedRunsResponseFromJSONTyped(json, false);
}

export function LegendDetectionQueuedRunsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LegendDetectionQueuedRunsResponse {
  if (json == null) {
    return json;
  }
  return {
    queued: json["queued"],
  };
}

export function LegendDetectionQueuedRunsResponseToJSON(
  json: any,
): LegendDetectionQueuedRunsResponse {
  return LegendDetectionQueuedRunsResponseToJSONTyped(json, false);
}

export function LegendDetectionQueuedRunsResponseToJSONTyped(
  value?: LegendDetectionQueuedRunsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    queued: value["queued"],
  };
}
