/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DetectedTeammate } from "./DetectedTeammate";
import {
  DetectedTeammateFromJSON,
  DetectedTeammateFromJSONTyped,
  DetectedTeammateToJSON,
  DetectedTeammateToJSONTyped,
} from "./DetectedTeammate";

/**
 *
 * @export
 * @interface LegendDetectionRun
 */
export interface LegendDetectionRun {
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  clipId: string;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  trigger: string;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  provider: string;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  model: string;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  reasoningEffort: string | null;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  promptVersion: string | null;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  status: string;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionRun
   */
  attempts: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionRun
   */
  frameCount: number | null;
  /**
   *
   * @type {boolean}
   * @memberof LegendDetectionRun
   */
  hudDetected: boolean | null;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  playerLegend: string | null;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionRun
   */
  playerLegendConfidence: number | null;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  playerName: string | null;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionRun
   */
  playerNameConfidence: number | null;
  /**
   *
   * @type {Array<DetectedTeammate>}
   * @memberof LegendDetectionRun
   */
  teammates: Array<DetectedTeammate>;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  rawResponse: string | null;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionRun
   */
  inputTokens: number | null;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionRun
   */
  cachedInputTokens: number | null;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionRun
   */
  outputTokens: number | null;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionRun
   */
  durationMs: number | null;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionRun
   */
  error: string | null;
  /**
   *
   * @type {Date}
   * @memberof LegendDetectionRun
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof LegendDetectionRun
   */
  completedAt: Date | null;
}

/**
 * Check if a given object implements the LegendDetectionRun interface.
 */
export function instanceOfLegendDetectionRun(
  value: object,
): value is LegendDetectionRun {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("clipId" in value) || value["clipId"] === undefined) return false;
  if (!("trigger" in value) || value["trigger"] === undefined) return false;
  if (!("provider" in value) || value["provider"] === undefined) return false;
  if (!("model" in value) || value["model"] === undefined) return false;
  if (!("reasoningEffort" in value) || value["reasoningEffort"] === undefined)
    return false;
  if (!("promptVersion" in value) || value["promptVersion"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("attempts" in value) || value["attempts"] === undefined) return false;
  if (!("frameCount" in value) || value["frameCount"] === undefined)
    return false;
  if (!("hudDetected" in value) || value["hudDetected"] === undefined)
    return false;
  if (!("playerLegend" in value) || value["playerLegend"] === undefined)
    return false;
  if (
    !("playerLegendConfidence" in value) ||
    value["playerLegendConfidence"] === undefined
  )
    return false;
  if (!("playerName" in value) || value["playerName"] === undefined)
    return false;
  if (
    !("playerNameConfidence" in value) ||
    value["playerNameConfidence"] === undefined
  )
    return false;
  if (!("teammates" in value) || value["teammates"] === undefined) return false;
  if (!("rawResponse" in value) || value["rawResponse"] === undefined)
    return false;
  if (!("inputTokens" in value) || value["inputTokens"] === undefined)
    return false;
  if (
    !("cachedInputTokens" in value) ||
    value["cachedInputTokens"] === undefined
  )
    return false;
  if (!("outputTokens" in value) || value["outputTokens"] === undefined)
    return false;
  if (!("durationMs" in value) || value["durationMs"] === undefined)
    return false;
  if (!("error" in value) || value["error"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("completedAt" in value) || value["completedAt"] === undefined)
    return false;
  return true;
}

export function LegendDetectionRunFromJSON(json: any): LegendDetectionRun {
  return LegendDetectionRunFromJSONTyped(json, false);
}

export function LegendDetectionRunFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LegendDetectionRun {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    clipId: json["clip_id"],
    trigger: json["trigger"],
    provider: json["provider"],
    model: json["model"],
    reasoningEffort: json["reasoning_effort"],
    promptVersion: json["prompt_version"],
    status: json["status"],
    attempts: json["attempts"],
    frameCount: json["frame_count"],
    hudDetected: json["hud_detected"],
    playerLegend: json["player_legend"],
    playerLegendConfidence: json["player_legend_confidence"],
    playerName: json["player_name"],
    playerNameConfidence: json["player_name_confidence"],
    teammates: (json["teammates"] as Array<any>).map(DetectedTeammateFromJSON),
    rawResponse: json["raw_response"],
    inputTokens: json["input_tokens"],
    cachedInputTokens: json["cached_input_tokens"],
    outputTokens: json["output_tokens"],
    durationMs: json["duration_ms"],
    error: json["error"],
    createdAt: new Date(json["created_at"]),
    completedAt:
      json["completed_at"] == null ? null : new Date(json["completed_at"]),
  };
}

export function LegendDetectionRunToJSON(json: any): LegendDetectionRun {
  return LegendDetectionRunToJSONTyped(json, false);
}

export function LegendDetectionRunToJSONTyped(
  value?: LegendDetectionRun | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    clip_id: value["clipId"],
    trigger: value["trigger"],
    provider: value["provider"],
    model: value["model"],
    reasoning_effort: value["reasoningEffort"],
    prompt_version: value["promptVersion"],
    status: value["status"],
    attempts: value["attempts"],
    frame_count: value["frameCount"],
    hud_detected: value["hudDetected"],
    player_legend: value["playerLegend"],
    player_legend_confidence: value["playerLegendConfidence"],
    player_name: value["playerName"],
    player_name_confidence: value["playerNameConfidence"],
    teammates: (value["teammates"] as Array<any>).map(DetectedTeammateToJSON),
    raw_response: value["rawResponse"],
    input_tokens: value["inputTokens"],
    cached_input_tokens: value["cachedInputTokens"],
    output_tokens: value["outputTokens"],
    duration_ms: value["durationMs"],
    error: value["error"],
    created_at: value["createdAt"].toISOString(),
    completed_at:
      value["completedAt"] == null
        ? value["completedAt"]
        : value["completedAt"].toISOString(),
  };
}
