/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LegendDetectionUsage
 */
export interface LegendDetectionUsage {
  /**
   *
   * @type {string}
   * @memberof LegendDetectionUsage
   */
  provider: string;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionUsage
   */
  model: string;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionUsage
   */
  reasoningEffort: string | null;
  /**
   *
   * @type {string}
   * @memberof LegendDetectionUsage
   */
  promptVersion: string | null;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  succeeded: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  failed: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  queued: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  inputTokens: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  cachedInputTokens: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  outputTokens: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  averageDurationMs: number | null;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  labelled: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  playerCorrect: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  squadLabelled: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  teammatesCorrect: number;
  /**
   *
   * @type {number}
   * @memberof LegendDetectionUsage
   */
  confidentMistakes: number;
  /**
   *
   * @type {Date}
   * @memberof LegendDetectionUsage
   */
  archivedAt: Date | null;
}

/**
 * Check if a given object implements the LegendDetectionUsage interface.
 */
export function instanceOfLegendDetectionUsage(
  value: object,
): value is LegendDetectionUsage {
  if (!("provider" in value) || value["provider"] === undefined) return false;
  if (!("model" in value) || value["model"] === undefined) return false;
  if (!("reasoningEffort" in value) || value["reasoningEffort"] === undefined)
    return false;
  if (!("promptVersion" in value) || value["promptVersion"] === undefined)
    return false;
  if (!("succeeded" in value) || value["succeeded"] === undefined) return false;
  if (!("failed" in value) || value["failed"] === undefined) return false;
  if (!("queued" in value) || value["queued"] === undefined) return false;
  if (!("inputTokens" in value) || value["inputTokens"] === undefined)
    return false;
  if (
    !("cachedInputTokens" in value) ||
    value["cachedInputTokens"] === undefined
  )
    return false;
  if (!("outputTokens" in value) || value["outputTokens"] === undefined)
    return false;
  if (
    !("averageDurationMs" in value) ||
    value["averageDurationMs"] === undefined
  )
    return false;
  if (!("labelled" in value) || value["labelled"] === undefined) return false;
  if (!("playerCorrect" in value) || value["playerCorrect"] === undefined)
    return false;
  if (!("squadLabelled" in value) || value["squadLabelled"] === undefined)
    return false;
  if (!("teammatesCorrect" in value) || value["teammatesCorrect"] === undefined)
    return false;
  if (
    !("confidentMistakes" in value) ||
    value["confidentMistakes"] === undefined
  )
    return false;
  if (!("archivedAt" in value) || value["archivedAt"] === undefined)
    return false;
  return true;
}

export function LegendDetectionUsageFromJSON(json: any): LegendDetectionUsage {
  return LegendDetectionUsageFromJSONTyped(json, false);
}

export function LegendDetectionUsageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LegendDetectionUsage {
  if (json == null) {
    return json;
  }
  return {
    provider: json["provider"],
    model: json["model"],
    reasoningEffort: json["reasoning_effort"],
    promptVersion: json["prompt_version"],
    succeeded: json["succeeded"],
    failed: json["failed"],
    queued: json["queued"],
    inputTokens: json["input_tokens"],
    cachedInputTokens: json["cached_input_tokens"],
    outputTokens: json["output_tokens"],
    averageDurationMs: json["average_duration_ms"],
    labelled: json["labelled"],
    playerCorrect: json["player_correct"],
    squadLabelled: json["squad_labelled"],
    teammatesCorrect: json["teammates_correct"],
    confidentMistakes: json["confident_mistakes"],
    archivedAt:
      json["archived_at"] == null ? null : new Date(json["archived_at"]),
  };
}

export function LegendDetectionUsageToJSON(json: any): LegendDetectionUsage {
  return LegendDetectionUsageToJSONTyped(json, false);
}

export function LegendDetectionUsageToJSONTyped(
  value?: LegendDetectionUsage | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    provider: value["provider"],
    model: value["model"],
    reasoning_effort: value["reasoningEffort"],
    prompt_version: value["promptVersion"],
    succeeded: value["succeeded"],
    failed: value["failed"],
    queued: value["queued"],
    input_tokens: value["inputTokens"],
    cached_input_tokens: value["cachedInputTokens"],
    output_tokens: value["outputTokens"],
    average_duration_ms: value["averageDurationMs"],
    labelled: value["labelled"],
    player_correct: value["playerCorrect"],
    squad_labelled: value["squadLabelled"],
    teammates_correct: value["teammatesCorrect"],
    confident_mistakes: value["confidentMistakes"],
    archived_at:
      value["archivedAt"] == null
        ? value["archivedAt"]
        : value["archivedAt"].toISOString(),
  };
}
