/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PlaylistPreviewClip } from "./PlaylistPreviewClip";
import {
  PlaylistPreviewClipFromJSON,
  PlaylistPreviewClipFromJSONTyped,
  PlaylistPreviewClipToJSON,
  PlaylistPreviewClipToJSONTyped,
} from "./PlaylistPreviewClip";
import type { PlaylistGameCount } from "./PlaylistGameCount";
import {
  PlaylistGameCountFromJSON,
  PlaylistGameCountFromJSONTyped,
  PlaylistGameCountToJSON,
  PlaylistGameCountToJSONTyped,
} from "./PlaylistGameCount";
import type { PlaylistPerson } from "./PlaylistPerson";
import {
  PlaylistPersonFromJSON,
  PlaylistPersonFromJSONTyped,
  PlaylistPersonToJSON,
  PlaylistPersonToJSONTyped,
} from "./PlaylistPerson";

/**
 *
 * @export
 * @interface PlaylistSummary
 */
export interface PlaylistSummary {
  /**
   *
   * @type {string}
   * @memberof PlaylistSummary
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof PlaylistSummary
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof PlaylistSummary
   */
  description: string | null;
  /**
   *
   * @type {string}
   * @memberof PlaylistSummary
   */
  creatorUserId: string;
  /**
   *
   * @type {Date}
   * @memberof PlaylistSummary
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof PlaylistSummary
   */
  updatedAt: Date;
  /**
   *
   * @type {number}
   * @memberof PlaylistSummary
   */
  clipCount: number;
  /**
   *
   * @type {number}
   * @memberof PlaylistSummary
   */
  collaboratorCount: number;
  /**
   *
   * @type {boolean}
   * @memberof PlaylistSummary
   */
  isGamingSession: boolean;
  /**
   *
   * @type {number}
   * @memberof PlaylistSummary
   */
  totalSeconds: number;
  /**
   *
   * @type {Array<PlaylistPreviewClip>}
   * @memberof PlaylistSummary
   */
  previewClips: Array<PlaylistPreviewClip>;
  /**
   *
   * @type {Array<PlaylistGameCount>}
   * @memberof PlaylistSummary
   */
  games: Array<PlaylistGameCount>;
  /**
   *
   * @type {Array<PlaylistPerson>}
   * @memberof PlaylistSummary
   */
  people: Array<PlaylistPerson>;
}

/**
 * Check if a given object implements the PlaylistSummary interface.
 */
export function instanceOfPlaylistSummary(
  value: object,
): value is PlaylistSummary {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("creatorUserId" in value) || value["creatorUserId"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("clipCount" in value) || value["clipCount"] === undefined) return false;
  if (
    !("collaboratorCount" in value) ||
    value["collaboratorCount"] === undefined
  )
    return false;
  if (!("isGamingSession" in value) || value["isGamingSession"] === undefined)
    return false;
  if (!("totalSeconds" in value) || value["totalSeconds"] === undefined)
    return false;
  if (!("previewClips" in value) || value["previewClips"] === undefined)
    return false;
  if (!("games" in value) || value["games"] === undefined) return false;
  if (!("people" in value) || value["people"] === undefined) return false;
  return true;
}

export function PlaylistSummaryFromJSON(json: any): PlaylistSummary {
  return PlaylistSummaryFromJSONTyped(json, false);
}

export function PlaylistSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlaylistSummary {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    description: json["description"],
    creatorUserId: json["creator_user_id"],
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"]),
    clipCount: json["clip_count"],
    collaboratorCount: json["collaborator_count"],
    isGamingSession: json["is_gaming_session"],
    totalSeconds: json["total_seconds"],
    previewClips: (json["preview_clips"] as Array<any>).map(
      PlaylistPreviewClipFromJSON,
    ),
    games: (json["games"] as Array<any>).map(PlaylistGameCountFromJSON),
    people: (json["people"] as Array<any>).map(PlaylistPersonFromJSON),
  };
}

export function PlaylistSummaryToJSON(json: any): PlaylistSummary {
  return PlaylistSummaryToJSONTyped(json, false);
}

export function PlaylistSummaryToJSONTyped(
  value?: PlaylistSummary | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    description: value["description"],
    creator_user_id: value["creatorUserId"],
    created_at: value["createdAt"].toISOString(),
    updated_at: value["updatedAt"].toISOString(),
    clip_count: value["clipCount"],
    collaborator_count: value["collaboratorCount"],
    is_gaming_session: value["isGamingSession"],
    total_seconds: value["totalSeconds"],
    preview_clips: (value["previewClips"] as Array<any>).map(
      PlaylistPreviewClipToJSON,
    ),
    games: (value["games"] as Array<any>).map(PlaylistGameCountToJSON),
    people: (value["people"] as Array<any>).map(PlaylistPersonToJSON),
  };
}
