/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlaylistPreviewClip
 */
export interface PlaylistPreviewClip {
  /**
   *
   * @type {string}
   * @memberof PlaylistPreviewClip
   */
  clipId: string;
  /**
   *
   * @type {string}
   * @memberof PlaylistPreviewClip
   */
  videoId: string;
}

/**
 * Check if a given object implements the PlaylistPreviewClip interface.
 */
export function instanceOfPlaylistPreviewClip(
  value: object,
): value is PlaylistPreviewClip {
  if (!("clipId" in value) || value["clipId"] === undefined) return false;
  if (!("videoId" in value) || value["videoId"] === undefined) return false;
  return true;
}

export function PlaylistPreviewClipFromJSON(json: any): PlaylistPreviewClip {
  return PlaylistPreviewClipFromJSONTyped(json, false);
}

export function PlaylistPreviewClipFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlaylistPreviewClip {
  if (json == null) {
    return json;
  }
  return {
    clipId: json["clip_id"],
    videoId: json["video_id"],
  };
}

export function PlaylistPreviewClipToJSON(json: any): PlaylistPreviewClip {
  return PlaylistPreviewClipToJSONTyped(json, false);
}

export function PlaylistPreviewClipToJSONTyped(
  value?: PlaylistPreviewClip | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clip_id: value["clipId"],
    video_id: value["videoId"],
  };
}
