/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlaylistCollaborator
 */
export interface PlaylistCollaborator {
  /**
   *
   * @type {string}
   * @memberof PlaylistCollaborator
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof PlaylistCollaborator
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof PlaylistCollaborator
   */
  avatarUrl: string | null;
  /**
   *
   * @type {Date}
   * @memberof PlaylistCollaborator
   */
  addedAt: Date;
  /**
   *
   * @type {string}
   * @memberof PlaylistCollaborator
   */
  addedByUserId: string;
}

/**
 * Check if a given object implements the PlaylistCollaborator interface.
 */
export function instanceOfPlaylistCollaborator(
  value: object,
): value is PlaylistCollaborator {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("username" in value) || value["username"] === undefined) return false;
  if (!("avatarUrl" in value) || value["avatarUrl"] === undefined) return false;
  if (!("addedAt" in value) || value["addedAt"] === undefined) return false;
  if (!("addedByUserId" in value) || value["addedByUserId"] === undefined)
    return false;
  return true;
}

export function PlaylistCollaboratorFromJSON(json: any): PlaylistCollaborator {
  return PlaylistCollaboratorFromJSONTyped(json, false);
}

export function PlaylistCollaboratorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlaylistCollaborator {
  if (json == null) {
    return json;
  }
  return {
    userId: json["user_id"],
    username: json["username"],
    avatarUrl: json["avatar_url"],
    addedAt: new Date(json["added_at"]),
    addedByUserId: json["added_by_user_id"],
  };
}

export function PlaylistCollaboratorToJSON(json: any): PlaylistCollaborator {
  return PlaylistCollaboratorToJSONTyped(json, false);
}

export function PlaylistCollaboratorToJSONTyped(
  value?: PlaylistCollaborator | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user_id: value["userId"],
    username: value["username"],
    avatar_url: value["avatarUrl"],
    added_at: value["addedAt"].toISOString(),
    added_by_user_id: value["addedByUserId"],
  };
}
