/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Playlist
 */
export interface Playlist {
  /**
   *
   * @type {string}
   * @memberof Playlist
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Playlist
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Playlist
   */
  description: string | null;
  /**
   *
   * @type {string}
   * @memberof Playlist
   */
  creatorUserId: string;
  /**
   *
   * @type {Date}
   * @memberof Playlist
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Playlist
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the Playlist interface.
 */
export function instanceOfPlaylist(value: object): value is Playlist {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("creatorUserId" in value) || value["creatorUserId"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function PlaylistFromJSON(json: any): Playlist {
  return PlaylistFromJSONTyped(json, false);
}

export function PlaylistFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Playlist {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    description: json["description"],
    creatorUserId: json["creator_user_id"],
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function PlaylistToJSON(json: any): Playlist {
  return PlaylistToJSONTyped(json, false);
}

export function PlaylistToJSONTyped(
  value?: Playlist | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    description: value["description"],
    creator_user_id: value["creatorUserId"],
    created_at: value["createdAt"].toISOString(),
    updated_at: value["updatedAt"].toISOString(),
  };
}
