/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface QueueLegendDetectionRunRequest
 */
export interface QueueLegendDetectionRunRequest {
  /**
   *
   * @type {string}
   * @memberof QueueLegendDetectionRunRequest
   */
  provider: string | null;
  /**
   *
   * @type {string}
   * @memberof QueueLegendDetectionRunRequest
   */
  model: string | null;
}

/**
 * Check if a given object implements the QueueLegendDetectionRunRequest interface.
 */
export function instanceOfQueueLegendDetectionRunRequest(
  value: object,
): value is QueueLegendDetectionRunRequest {
  if (!("provider" in value) || value["provider"] === undefined) return false;
  if (!("model" in value) || value["model"] === undefined) return false;
  return true;
}

export function QueueLegendDetectionRunRequestFromJSON(
  json: any,
): QueueLegendDetectionRunRequest {
  return QueueLegendDetectionRunRequestFromJSONTyped(json, false);
}

export function QueueLegendDetectionRunRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QueueLegendDetectionRunRequest {
  if (json == null) {
    return json;
  }
  return {
    provider: json["provider"],
    model: json["model"],
  };
}

export function QueueLegendDetectionRunRequestToJSON(
  json: any,
): QueueLegendDetectionRunRequest {
  return QueueLegendDetectionRunRequestToJSONTyped(json, false);
}

export function QueueLegendDetectionRunRequestToJSONTyped(
  value?: QueueLegendDetectionRunRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    provider: value["provider"],
    model: value["model"],
  };
}
