/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface QueueClipTranscriptionRunRequest
 */
export interface QueueClipTranscriptionRunRequest {
  /**
   *
   * @type {string}
   * @memberof QueueClipTranscriptionRunRequest
   */
  model: string | null;
}

/**
 * Check if a given object implements the QueueClipTranscriptionRunRequest interface.
 */
export function instanceOfQueueClipTranscriptionRunRequest(
  value: object,
): value is QueueClipTranscriptionRunRequest {
  if (!("model" in value) || value["model"] === undefined) return false;
  return true;
}

export function QueueClipTranscriptionRunRequestFromJSON(
  json: any,
): QueueClipTranscriptionRunRequest {
  return QueueClipTranscriptionRunRequestFromJSONTyped(json, false);
}

export function QueueClipTranscriptionRunRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QueueClipTranscriptionRunRequest {
  if (json == null) {
    return json;
  }
  return {
    model: json["model"],
  };
}

export function QueueClipTranscriptionRunRequestToJSON(
  json: any,
): QueueClipTranscriptionRunRequest {
  return QueueClipTranscriptionRunRequestToJSONTyped(json, false);
}

export function QueueClipTranscriptionRunRequestToJSONTyped(
  value?: QueueClipTranscriptionRunRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    model: value["model"],
  };
}
