/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface QueueClipSummaryRunRequest
 */
export interface QueueClipSummaryRunRequest {
  /**
   *
   * @type {string}
   * @memberof QueueClipSummaryRunRequest
   */
  provider: string | null;
  /**
   *
   * @type {string}
   * @memberof QueueClipSummaryRunRequest
   */
  model: string | null;
  /**
   *
   * @type {string}
   * @memberof QueueClipSummaryRunRequest
   */
  reasoningEffort: string | null;
}

/**
 * Check if a given object implements the QueueClipSummaryRunRequest interface.
 */
export function instanceOfQueueClipSummaryRunRequest(
  value: object,
): value is QueueClipSummaryRunRequest {
  if (!("provider" in value) || value["provider"] === undefined) return false;
  if (!("model" in value) || value["model"] === undefined) return false;
  if (!("reasoningEffort" in value) || value["reasoningEffort"] === undefined)
    return false;
  return true;
}

export function QueueClipSummaryRunRequestFromJSON(
  json: any,
): QueueClipSummaryRunRequest {
  return QueueClipSummaryRunRequestFromJSONTyped(json, false);
}

export function QueueClipSummaryRunRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QueueClipSummaryRunRequest {
  if (json == null) {
    return json;
  }
  return {
    provider: json["provider"],
    model: json["model"],
    reasoningEffort: json["reasoning_effort"],
  };
}

export function QueueClipSummaryRunRequestToJSON(
  json: any,
): QueueClipSummaryRunRequest {
  return QueueClipSummaryRunRequestToJSONTyped(json, false);
}

export function QueueClipSummaryRunRequestToJSONTyped(
  value?: QueueClipSummaryRunRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    provider: value["provider"],
    model: value["model"],
    reasoning_effort: value["reasoningEffort"],
  };
}
