/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ReorderPlaylistClipsRequest
 */
export interface ReorderPlaylistClipsRequest {
  /**
   *
   * @type {string}
   * @memberof ReorderPlaylistClipsRequest
   */
  clipId?: string | null;
  /**
   *
   * @type {number}
   * @memberof ReorderPlaylistClipsRequest
   */
  newPosition?: number | null;
  /**
   *
   * @type {Array<string>}
   * @memberof ReorderPlaylistClipsRequest
   */
  clipOrdering?: Array<string> | null;
}

/**
 * Check if a given object implements the ReorderPlaylistClipsRequest interface.
 */
export function instanceOfReorderPlaylistClipsRequest(
  value: object,
): value is ReorderPlaylistClipsRequest {
  return true;
}

export function ReorderPlaylistClipsRequestFromJSON(
  json: any,
): ReorderPlaylistClipsRequest {
  return ReorderPlaylistClipsRequestFromJSONTyped(json, false);
}

export function ReorderPlaylistClipsRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReorderPlaylistClipsRequest {
  if (json == null) {
    return json;
  }
  return {
    clipId: json["clip_id"] == null ? undefined : json["clip_id"],
    newPosition:
      json["new_position"] == null ? undefined : json["new_position"],
    clipOrdering:
      json["clip_ordering"] == null ? undefined : json["clip_ordering"],
  };
}

export function ReorderPlaylistClipsRequestToJSON(
  json: any,
): ReorderPlaylistClipsRequest {
  return ReorderPlaylistClipsRequestToJSONTyped(json, false);
}

export function ReorderPlaylistClipsRequestToJSONTyped(
  value?: ReorderPlaylistClipsRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    clip_id: value["clipId"],
    new_position: value["newPosition"],
    clip_ordering: value["clipOrdering"],
  };
}
