/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RoomTokenResponse
 */
export interface RoomTokenResponse {
  /**
   *
   * @type {string}
   * @memberof RoomTokenResponse
   */
  roomToken: string;
  /**
   *
   * @type {Date}
   * @memberof RoomTokenResponse
   */
  roomTokenExpiresAt: Date;
}

/**
 * Check if a given object implements the RoomTokenResponse interface.
 */
export function instanceOfRoomTokenResponse(
  value: object,
): value is RoomTokenResponse {
  if (!("roomToken" in value) || value["roomToken"] === undefined) return false;
  if (
    !("roomTokenExpiresAt" in value) ||
    value["roomTokenExpiresAt"] === undefined
  )
    return false;
  return true;
}

export function RoomTokenResponseFromJSON(json: any): RoomTokenResponse {
  return RoomTokenResponseFromJSONTyped(json, false);
}

export function RoomTokenResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RoomTokenResponse {
  if (json == null) {
    return json;
  }
  return {
    roomToken: json["room_token"],
    roomTokenExpiresAt: new Date(json["room_token_expires_at"]),
  };
}

export function RoomTokenResponseToJSON(json: any): RoomTokenResponse {
  return RoomTokenResponseToJSONTyped(json, false);
}

export function RoomTokenResponseToJSONTyped(
  value?: RoomTokenResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    room_token: value["roomToken"],
    room_token_expires_at: value["roomTokenExpiresAt"].toISOString(),
  };
}
