/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SetEmailRequest
 */
export interface SetEmailRequest {
  /**
   *
   * @type {string}
   * @memberof SetEmailRequest
   */
  email: string | null;
}

/**
 * Check if a given object implements the SetEmailRequest interface.
 */
export function instanceOfSetEmailRequest(
  value: object,
): value is SetEmailRequest {
  if (!("email" in value) || value["email"] === undefined) return false;
  return true;
}

export function SetEmailRequestFromJSON(json: any): SetEmailRequest {
  return SetEmailRequestFromJSONTyped(json, false);
}

export function SetEmailRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SetEmailRequest {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"],
  };
}

export function SetEmailRequestToJSON(json: any): SetEmailRequest {
  return SetEmailRequestToJSONTyped(json, false);
}

export function SetEmailRequestToJSONTyped(
  value?: SetEmailRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
  };
}
