/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SetLegendDetectionLabelRequest
 */
export interface SetLegendDetectionLabelRequest {
  /**
   *
   * @type {string}
   * @memberof SetLegendDetectionLabelRequest
   */
  playerLegend: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof SetLegendDetectionLabelRequest
   */
  teammateLegends: Array<string>;
}

/**
 * Check if a given object implements the SetLegendDetectionLabelRequest interface.
 */
export function instanceOfSetLegendDetectionLabelRequest(
  value: object,
): value is SetLegendDetectionLabelRequest {
  if (!("playerLegend" in value) || value["playerLegend"] === undefined)
    return false;
  if (!("teammateLegends" in value) || value["teammateLegends"] === undefined)
    return false;
  return true;
}

export function SetLegendDetectionLabelRequestFromJSON(
  json: any,
): SetLegendDetectionLabelRequest {
  return SetLegendDetectionLabelRequestFromJSONTyped(json, false);
}

export function SetLegendDetectionLabelRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SetLegendDetectionLabelRequest {
  if (json == null) {
    return json;
  }
  return {
    playerLegend: json["player_legend"],
    teammateLegends: json["teammate_legends"],
  };
}

export function SetLegendDetectionLabelRequestToJSON(
  json: any,
): SetLegendDetectionLabelRequest {
  return SetLegendDetectionLabelRequestToJSONTyped(json, false);
}

export function SetLegendDetectionLabelRequestToJSONTyped(
  value?: SetLegendDetectionLabelRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    player_legend: value["playerLegend"],
    teammate_legends: value["teammateLegends"],
  };
}
