/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StorageUsageResponse
 */
export interface StorageUsageResponse {
  /**
   *
   * @type {number}
   * @memberof StorageUsageResponse
   */
  usedBytes: number;
  /**
   *
   * @type {number}
   * @memberof StorageUsageResponse
   */
  limitBytes: number | null;
  /**
   *
   * @type {boolean}
   * @memberof StorageUsageResponse
   */
  isUnlimited: boolean;
}

/**
 * Check if a given object implements the StorageUsageResponse interface.
 */
export function instanceOfStorageUsageResponse(
  value: object,
): value is StorageUsageResponse {
  if (!("usedBytes" in value) || value["usedBytes"] === undefined) return false;
  if (!("limitBytes" in value) || value["limitBytes"] === undefined)
    return false;
  if (!("isUnlimited" in value) || value["isUnlimited"] === undefined)
    return false;
  return true;
}

export function StorageUsageResponseFromJSON(json: any): StorageUsageResponse {
  return StorageUsageResponseFromJSONTyped(json, false);
}

export function StorageUsageResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StorageUsageResponse {
  if (json == null) {
    return json;
  }
  return {
    usedBytes: json["used_bytes"],
    limitBytes: json["limit_bytes"],
    isUnlimited: json["is_unlimited"],
  };
}

export function StorageUsageResponseToJSON(json: any): StorageUsageResponse {
  return StorageUsageResponseToJSONTyped(json, false);
}

export function StorageUsageResponseToJSONTyped(
  value?: StorageUsageResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    used_bytes: value["usedBytes"],
    limit_bytes: value["limitBytes"],
    is_unlimited: value["isUnlimited"],
  };
}
