/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TopTag
 */
export interface TopTag {
  /**
   *
   * @type {string}
   * @memberof TopTag
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof TopTag
   */
  count: number;
}

/**
 * Check if a given object implements the TopTag interface.
 */
export function instanceOfTopTag(value: object): value is TopTag {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("count" in value) || value["count"] === undefined) return false;
  return true;
}

export function TopTagFromJSON(json: any): TopTag {
  return TopTagFromJSONTyped(json, false);
}

export function TopTagFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TopTag {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    count: json["count"],
  };
}

export function TopTagToJSON(json: any): TopTag {
  return TopTagToJSONTyped(json, false);
}

export function TopTagToJSONTyped(
  value?: TopTag | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    count: value["count"],
  };
}
