/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TwitchClipSummary
 */
export interface TwitchClipSummary {
  /**
   *
   * @type {string}
   * @memberof TwitchClipSummary
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof TwitchClipSummary
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof TwitchClipSummary
   */
  url: string;
  /**
   *
   * @type {string}
   * @memberof TwitchClipSummary
   */
  thumbnailUrl: string | null;
  /**
   *
   * @type {number}
   * @memberof TwitchClipSummary
   */
  durationSeconds: number;
  /**
   *
   * @type {number}
   * @memberof TwitchClipSummary
   */
  viewCount: number;
  /**
   *
   * @type {Date}
   * @memberof TwitchClipSummary
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof TwitchClipSummary
   */
  creatorName: string | null;
  /**
   *
   * @type {string}
   * @memberof TwitchClipSummary
   */
  gameName: string | null;
  /**
   *
   * @type {number}
   * @memberof TwitchClipSummary
   */
  igdbId: number | null;
  /**
   *
   * @type {string}
   * @memberof TwitchClipSummary
   */
  suggestedCategoryId: string | null;
  /**
   *
   * @type {boolean}
   * @memberof TwitchClipSummary
   */
  alreadyImported: boolean;
}

/**
 * Check if a given object implements the TwitchClipSummary interface.
 */
export function instanceOfTwitchClipSummary(
  value: object,
): value is TwitchClipSummary {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("url" in value) || value["url"] === undefined) return false;
  if (!("thumbnailUrl" in value) || value["thumbnailUrl"] === undefined)
    return false;
  if (!("durationSeconds" in value) || value["durationSeconds"] === undefined)
    return false;
  if (!("viewCount" in value) || value["viewCount"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("creatorName" in value) || value["creatorName"] === undefined)
    return false;
  if (!("gameName" in value) || value["gameName"] === undefined) return false;
  if (!("igdbId" in value) || value["igdbId"] === undefined) return false;
  if (
    !("suggestedCategoryId" in value) ||
    value["suggestedCategoryId"] === undefined
  )
    return false;
  if (!("alreadyImported" in value) || value["alreadyImported"] === undefined)
    return false;
  return true;
}

export function TwitchClipSummaryFromJSON(json: any): TwitchClipSummary {
  return TwitchClipSummaryFromJSONTyped(json, false);
}

export function TwitchClipSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TwitchClipSummary {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    title: json["title"],
    url: json["url"],
    thumbnailUrl: json["thumbnail_url"],
    durationSeconds: json["duration_seconds"],
    viewCount: json["view_count"],
    createdAt: new Date(json["created_at"]),
    creatorName: json["creator_name"],
    gameName: json["game_name"],
    igdbId: json["igdb_id"],
    suggestedCategoryId: json["suggested_category_id"],
    alreadyImported: json["already_imported"],
  };
}

export function TwitchClipSummaryToJSON(json: any): TwitchClipSummary {
  return TwitchClipSummaryToJSONTyped(json, false);
}

export function TwitchClipSummaryToJSONTyped(
  value?: TwitchClipSummary | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    title: value["title"],
    url: value["url"],
    thumbnail_url: value["thumbnailUrl"],
    duration_seconds: value["durationSeconds"],
    view_count: value["viewCount"],
    created_at: value["createdAt"].toISOString(),
    creator_name: value["creatorName"],
    game_name: value["gameName"],
    igdb_id: value["igdbId"],
    suggested_category_id: value["suggestedCategoryId"],
    already_imported: value["alreadyImported"],
  };
}
