/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
  /**
   *
   * @type {string}
   * @memberof UserProfile
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof UserProfile
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof UserProfile
   */
  globalName: string | null;
  /**
   *
   * @type {string}
   * @memberof UserProfile
   */
  avatar: string | null;
}

/**
 * Check if a given object implements the UserProfile interface.
 */
export function instanceOfUserProfile(value: object): value is UserProfile {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("username" in value) || value["username"] === undefined) return false;
  if (!("globalName" in value) || value["globalName"] === undefined)
    return false;
  if (!("avatar" in value) || value["avatar"] === undefined) return false;
  return true;
}

export function UserProfileFromJSON(json: any): UserProfile {
  return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserProfile {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    username: json["username"],
    globalName: json["global_name"],
    avatar: json["avatar"],
  };
}

export function UserProfileToJSON(json: any): UserProfile {
  return UserProfileToJSONTyped(json, false);
}

export function UserProfileToJSONTyped(
  value?: UserProfile | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    username: value["username"],
    global_name: value["globalName"],
    avatar: value["avatar"],
  };
}
