"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAddTagRequest = instanceOfAddTagRequest;
exports.AddTagRequestFromJSON = AddTagRequestFromJSON;
exports.AddTagRequestFromJSONTyped = AddTagRequestFromJSONTyped;
exports.AddTagRequestToJSON = AddTagRequestToJSON;
exports.AddTagRequestToJSONTyped = AddTagRequestToJSONTyped;
/**
 * Check if a given object implements the AddTagRequest interface.
 */
function instanceOfAddTagRequest(value) {
    if (!('tag' in value) || value['tag'] === undefined)
        return false;
    return true;
}
function AddTagRequestFromJSON(json) {
    return AddTagRequestFromJSONTyped(json, false);
}
function AddTagRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'tag': json['tag'],
    };
}
function AddTagRequestToJSON(json) {
    return AddTagRequestToJSONTyped(json, false);
}
function AddTagRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'tag': value['tag'],
    };
}
