/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BackupFileInfo } from './BackupFileInfo';
import {
    BackupFileInfoFromJSON,
    BackupFileInfoFromJSONTyped,
    BackupFileInfoToJSON,
    BackupFileInfoToJSONTyped,
} from './BackupFileInfo';

/**
 * 
 * @export
 * @interface BackupListResult
 */
export interface BackupListResult {
    /**
     * 
     * @type {boolean}
     * @memberof BackupListResult
     */
    isConfigured: boolean;
    /**
     * 
     * @type {Array<BackupFileInfo>}
     * @memberof BackupListResult
     */
    localFiles: Array<BackupFileInfo>;
    /**
     * 
     * @type {Array<any>}
     * @memberof BackupListResult
     */
    remoteFiles: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof BackupListResult
     */
    pendingSyncCount: number;
}

/**
 * Check if a given object implements the BackupListResult interface.
 */
export function instanceOfBackupListResult(value: object): value is BackupListResult {
    if (!('isConfigured' in value) || value['isConfigured'] === undefined) return false;
    if (!('localFiles' in value) || value['localFiles'] === undefined) return false;
    if (!('remoteFiles' in value) || value['remoteFiles'] === undefined) return false;
    if (!('pendingSyncCount' in value) || value['pendingSyncCount'] === undefined) return false;
    return true;
}

export function BackupListResultFromJSON(json: any): BackupListResult {
    return BackupListResultFromJSONTyped(json, false);
}

export function BackupListResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupListResult {
    if (json == null) {
        return json;
    }
    return {
        
        'isConfigured': json['is_configured'],
        'localFiles': ((json['local_files'] as Array<any>).map(BackupFileInfoFromJSON)),
        'remoteFiles': json['remote_files'],
        'pendingSyncCount': json['pending_sync_count'],
    };
}

export function BackupListResultToJSON(json: any): BackupListResult {
    return BackupListResultToJSONTyped(json, false);
}

export function BackupListResultToJSONTyped(value?: BackupListResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_configured': value['isConfigured'],
        'local_files': ((value['localFiles'] as Array<any>).map(BackupFileInfoToJSON)),
        'remote_files': value['remoteFiles'],
        'pending_sync_count': value['pendingSyncCount'],
    };
}

