/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Moment } from './Moment';
import {
    MomentFromJSON,
    MomentFromJSONTyped,
    MomentToJSON,
    MomentToJSONTyped,
} from './Moment';
import type { MetaTag } from './MetaTag';
import {
    MetaTagFromJSON,
    MetaTagFromJSONTyped,
    MetaTagToJSON,
    MetaTagToJSONTyped,
} from './MetaTag';

/**
 * 
 * @export
 * @interface BunnyVideo
 */
export interface BunnyVideo {
    /**
     * 
     * @type {number}
     * @memberof BunnyVideo
     */
    videoLibraryId: number;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    guid: string;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof BunnyVideo
     */
    dateUploaded: Date;
    /**
     * 
     * @type {number}
     * @memberof BunnyVideo
     */
    length: number;
    /**
     * 
     * @type {number}
     * @memberof BunnyVideo
     */
    status: number;
    /**
     * 
     * @type {number}
     * @memberof BunnyVideo
     */
    framerate: number;
    /**
     * 
     * @type {number}
     * @memberof BunnyVideo
     */
    thumbnailCount: number;
    /**
     * 
     * @type {number}
     * @memberof BunnyVideo
     */
    encodeProgress: number;
    /**
     * 
     * @type {number}
     * @memberof BunnyVideo
     */
    storageSize: number;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    thumbnailFileName: string;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    thumbnailBlurhash: string;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    category: string;
    /**
     * 
     * @type {Array<Moment>}
     * @memberof BunnyVideo
     */
    moments: Array<Moment>;
    /**
     * 
     * @type {Array<MetaTag>}
     * @memberof BunnyVideo
     */
    metaTags: Array<MetaTag>;
}

/**
 * Check if a given object implements the BunnyVideo interface.
 */
export function instanceOfBunnyVideo(value: object): value is BunnyVideo {
    if (!('videoLibraryId' in value) || value['videoLibraryId'] === undefined) return false;
    if (!('guid' in value) || value['guid'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('dateUploaded' in value) || value['dateUploaded'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('framerate' in value) || value['framerate'] === undefined) return false;
    if (!('thumbnailCount' in value) || value['thumbnailCount'] === undefined) return false;
    if (!('encodeProgress' in value) || value['encodeProgress'] === undefined) return false;
    if (!('storageSize' in value) || value['storageSize'] === undefined) return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('thumbnailFileName' in value) || value['thumbnailFileName'] === undefined) return false;
    if (!('thumbnailBlurhash' in value) || value['thumbnailBlurhash'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('moments' in value) || value['moments'] === undefined) return false;
    if (!('metaTags' in value) || value['metaTags'] === undefined) return false;
    return true;
}

export function BunnyVideoFromJSON(json: any): BunnyVideo {
    return BunnyVideoFromJSONTyped(json, false);
}

export function BunnyVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BunnyVideo {
    if (json == null) {
        return json;
    }
    return {
        
        'videoLibraryId': json['video_library_id'],
        'guid': json['guid'],
        'title': json['title'],
        'dateUploaded': (new Date(json['date_uploaded'])),
        'length': json['length'],
        'status': json['status'],
        'framerate': json['framerate'],
        'thumbnailCount': json['thumbnail_count'],
        'encodeProgress': json['encode_progress'],
        'storageSize': json['storage_size'],
        'collectionId': json['collection_id'],
        'thumbnailFileName': json['thumbnail_file_name'],
        'thumbnailBlurhash': json['thumbnail_blurhash'],
        'category': json['category'],
        'moments': ((json['moments'] as Array<any>).map(MomentFromJSON)),
        'metaTags': ((json['meta_tags'] as Array<any>).map(MetaTagFromJSON)),
    };
}

export function BunnyVideoToJSON(json: any): BunnyVideo {
    return BunnyVideoToJSONTyped(json, false);
}

export function BunnyVideoToJSONTyped(value?: BunnyVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video_library_id': value['videoLibraryId'],
        'guid': value['guid'],
        'title': value['title'],
        'date_uploaded': value['dateUploaded'].toISOString(),
        'length': value['length'],
        'status': value['status'],
        'framerate': value['framerate'],
        'thumbnail_count': value['thumbnailCount'],
        'encode_progress': value['encodeProgress'],
        'storage_size': value['storageSize'],
        'collection_id': value['collectionId'],
        'thumbnail_file_name': value['thumbnailFileName'],
        'thumbnail_blurhash': value['thumbnailBlurhash'],
        'category': value['category'],
        'moments': ((value['moments'] as Array<any>).map(MomentToJSON)),
        'meta_tags': ((value['metaTags'] as Array<any>).map(MetaTagToJSON)),
    };
}

