/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BunnyVideoStorageSize } from './BunnyVideoStorageSize';
import {
    BunnyVideoStorageSizeFromJSON,
    BunnyVideoStorageSizeFromJSONTyped,
    BunnyVideoStorageSizeToJSON,
    BunnyVideoStorageSizeToJSONTyped,
} from './BunnyVideoStorageSize';
import type { GetVideosByCategoryPageParameter } from './GetVideosByCategoryPageParameter';
import {
    GetVideosByCategoryPageParameterFromJSON,
    GetVideosByCategoryPageParameterFromJSONTyped,
    GetVideosByCategoryPageParameterToJSON,
    GetVideosByCategoryPageParameterToJSONTyped,
} from './GetVideosByCategoryPageParameter';
import type { Moment } from './Moment';
import {
    MomentFromJSON,
    MomentFromJSONTyped,
    MomentToJSON,
    MomentToJSONTyped,
} from './Moment';
import type { BunnyVideoFramerate } from './BunnyVideoFramerate';
import {
    BunnyVideoFramerateFromJSON,
    BunnyVideoFramerateFromJSONTyped,
    BunnyVideoFramerateToJSON,
    BunnyVideoFramerateToJSONTyped,
} from './BunnyVideoFramerate';
import type { MetaTag } from './MetaTag';
import {
    MetaTagFromJSON,
    MetaTagFromJSONTyped,
    MetaTagToJSON,
    MetaTagToJSONTyped,
} from './MetaTag';

/**
 * 
 * @export
 * @interface BunnyVideo
 */
export interface BunnyVideo {
    /**
     * 
     * @type {GetVideosByCategoryPageParameter}
     * @memberof BunnyVideo
     */
    videoLibraryId: GetVideosByCategoryPageParameter;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    guid: string;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof BunnyVideo
     */
    dateUploaded: Date;
    /**
     * 
     * @type {GetVideosByCategoryPageParameter}
     * @memberof BunnyVideo
     */
    length: GetVideosByCategoryPageParameter;
    /**
     * 
     * @type {GetVideosByCategoryPageParameter}
     * @memberof BunnyVideo
     */
    status: GetVideosByCategoryPageParameter;
    /**
     * 
     * @type {BunnyVideoFramerate}
     * @memberof BunnyVideo
     */
    framerate: BunnyVideoFramerate;
    /**
     * 
     * @type {GetVideosByCategoryPageParameter}
     * @memberof BunnyVideo
     */
    thumbnailCount: GetVideosByCategoryPageParameter;
    /**
     * 
     * @type {GetVideosByCategoryPageParameter}
     * @memberof BunnyVideo
     */
    encodeProgress: GetVideosByCategoryPageParameter;
    /**
     * 
     * @type {BunnyVideoStorageSize}
     * @memberof BunnyVideo
     */
    storageSize: BunnyVideoStorageSize;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    thumbnailFileName: string;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    thumbnailBlurhash: string;
    /**
     * 
     * @type {string}
     * @memberof BunnyVideo
     */
    category: string;
    /**
     * 
     * @type {Array<Moment>}
     * @memberof BunnyVideo
     */
    moments: Array<Moment>;
    /**
     * 
     * @type {Array<MetaTag>}
     * @memberof BunnyVideo
     */
    metaTags: Array<MetaTag>;
}

/**
 * Check if a given object implements the BunnyVideo interface.
 */
export function instanceOfBunnyVideo(value: object): value is BunnyVideo {
    if (!('videoLibraryId' in value) || value['videoLibraryId'] === undefined) return false;
    if (!('guid' in value) || value['guid'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('dateUploaded' in value) || value['dateUploaded'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('framerate' in value) || value['framerate'] === undefined) return false;
    if (!('thumbnailCount' in value) || value['thumbnailCount'] === undefined) return false;
    if (!('encodeProgress' in value) || value['encodeProgress'] === undefined) return false;
    if (!('storageSize' in value) || value['storageSize'] === undefined) return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('thumbnailFileName' in value) || value['thumbnailFileName'] === undefined) return false;
    if (!('thumbnailBlurhash' in value) || value['thumbnailBlurhash'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('moments' in value) || value['moments'] === undefined) return false;
    if (!('metaTags' in value) || value['metaTags'] === undefined) return false;
    return true;
}

export function BunnyVideoFromJSON(json: any): BunnyVideo {
    return BunnyVideoFromJSONTyped(json, false);
}

export function BunnyVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BunnyVideo {
    if (json == null) {
        return json;
    }
    return {
        
        'videoLibraryId': GetVideosByCategoryPageParameterFromJSON(json['video_library_id']),
        'guid': json['guid'],
        'title': json['title'],
        'dateUploaded': (new Date(json['date_uploaded'])),
        'length': GetVideosByCategoryPageParameterFromJSON(json['length']),
        'status': GetVideosByCategoryPageParameterFromJSON(json['status']),
        'framerate': BunnyVideoFramerateFromJSON(json['framerate']),
        'thumbnailCount': GetVideosByCategoryPageParameterFromJSON(json['thumbnail_count']),
        'encodeProgress': GetVideosByCategoryPageParameterFromJSON(json['encode_progress']),
        'storageSize': BunnyVideoStorageSizeFromJSON(json['storage_size']),
        'collectionId': json['collection_id'],
        'thumbnailFileName': json['thumbnail_file_name'],
        'thumbnailBlurhash': json['thumbnail_blurhash'],
        'category': json['category'],
        'moments': ((json['moments'] as Array<any>).map(MomentFromJSON)),
        'metaTags': ((json['meta_tags'] as Array<any>).map(MetaTagFromJSON)),
    };
}

export function BunnyVideoToJSON(json: any): BunnyVideo {
    return BunnyVideoToJSONTyped(json, false);
}

export function BunnyVideoToJSONTyped(value?: BunnyVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video_library_id': GetVideosByCategoryPageParameterToJSON(value['videoLibraryId']),
        'guid': value['guid'],
        'title': value['title'],
        'date_uploaded': value['dateUploaded'].toISOString(),
        'length': GetVideosByCategoryPageParameterToJSON(value['length']),
        'status': GetVideosByCategoryPageParameterToJSON(value['status']),
        'framerate': BunnyVideoFramerateToJSON(value['framerate']),
        'thumbnail_count': GetVideosByCategoryPageParameterToJSON(value['thumbnailCount']),
        'encode_progress': GetVideosByCategoryPageParameterToJSON(value['encodeProgress']),
        'storage_size': BunnyVideoStorageSizeToJSON(value['storageSize']),
        'collection_id': value['collectionId'],
        'thumbnail_file_name': value['thumbnailFileName'],
        'thumbnail_blurhash': value['thumbnailBlurhash'],
        'category': value['category'],
        'moments': ((value['moments'] as Array<any>).map(MomentToJSON)),
        'meta_tags': ((value['metaTags'] as Array<any>).map(MetaTagToJSON)),
    };
}

