"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfBunnyVideo = instanceOfBunnyVideo;
exports.BunnyVideoFromJSON = BunnyVideoFromJSON;
exports.BunnyVideoFromJSONTyped = BunnyVideoFromJSONTyped;
exports.BunnyVideoToJSON = BunnyVideoToJSON;
exports.BunnyVideoToJSONTyped = BunnyVideoToJSONTyped;
var Moment_1 = require("./Moment");
var MetaTag_1 = require("./MetaTag");
/**
 * Check if a given object implements the BunnyVideo interface.
 */
function instanceOfBunnyVideo(value) {
    if (!('videoLibraryId' in value) || value['videoLibraryId'] === undefined)
        return false;
    if (!('guid' in value) || value['guid'] === undefined)
        return false;
    if (!('title' in value) || value['title'] === undefined)
        return false;
    if (!('dateUploaded' in value) || value['dateUploaded'] === undefined)
        return false;
    if (!('length' in value) || value['length'] === undefined)
        return false;
    if (!('status' in value) || value['status'] === undefined)
        return false;
    if (!('framerate' in value) || value['framerate'] === undefined)
        return false;
    if (!('thumbnailCount' in value) || value['thumbnailCount'] === undefined)
        return false;
    if (!('encodeProgress' in value) || value['encodeProgress'] === undefined)
        return false;
    if (!('storageSize' in value) || value['storageSize'] === undefined)
        return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined)
        return false;
    if (!('thumbnailFileName' in value) || value['thumbnailFileName'] === undefined)
        return false;
    if (!('thumbnailBlurhash' in value) || value['thumbnailBlurhash'] === undefined)
        return false;
    if (!('category' in value) || value['category'] === undefined)
        return false;
    if (!('moments' in value) || value['moments'] === undefined)
        return false;
    if (!('metaTags' in value) || value['metaTags'] === undefined)
        return false;
    return true;
}
function BunnyVideoFromJSON(json) {
    return BunnyVideoFromJSONTyped(json, false);
}
function BunnyVideoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'videoLibraryId': json['video_library_id'],
        'guid': json['guid'],
        'title': json['title'],
        'dateUploaded': (new Date(json['date_uploaded'])),
        'length': json['length'],
        'status': json['status'],
        'framerate': json['framerate'],
        'thumbnailCount': json['thumbnail_count'],
        'encodeProgress': json['encode_progress'],
        'storageSize': json['storage_size'],
        'collectionId': json['collection_id'],
        'thumbnailFileName': json['thumbnail_file_name'],
        'thumbnailBlurhash': json['thumbnail_blurhash'],
        'category': json['category'],
        'moments': (json['moments'].map(Moment_1.MomentFromJSON)),
        'metaTags': (json['meta_tags'].map(MetaTag_1.MetaTagFromJSON)),
    };
}
function BunnyVideoToJSON(json) {
    return BunnyVideoToJSONTyped(json, false);
}
function BunnyVideoToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'video_library_id': value['videoLibraryId'],
        'guid': value['guid'],
        'title': value['title'],
        'date_uploaded': value['dateUploaded'].toISOString(),
        'length': value['length'],
        'status': value['status'],
        'framerate': value['framerate'],
        'thumbnail_count': value['thumbnailCount'],
        'encode_progress': value['encodeProgress'],
        'storage_size': value['storageSize'],
        'collection_id': value['collectionId'],
        'thumbnail_file_name': value['thumbnailFileName'],
        'thumbnail_blurhash': value['thumbnailBlurhash'],
        'category': value['category'],
        'moments': (value['moments'].map(Moment_1.MomentToJSON)),
        'meta_tags': (value['metaTags'].map(MetaTag_1.MetaTagToJSON)),
    };
}
