/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BunnyVideoStorageSize
 */
export interface BunnyVideoStorageSize {
}

/**
 * Check if a given object implements the BunnyVideoStorageSize interface.
 */
export function instanceOfBunnyVideoStorageSize(value: object): value is BunnyVideoStorageSize {
    return true;
}

export function BunnyVideoStorageSizeFromJSON(json: any): BunnyVideoStorageSize {
    return BunnyVideoStorageSizeFromJSONTyped(json, false);
}

export function BunnyVideoStorageSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BunnyVideoStorageSize {
    return json;
}

export function BunnyVideoStorageSizeToJSON(json: any): BunnyVideoStorageSize {
    return BunnyVideoStorageSizeToJSONTyped(json, false);
}

export function BunnyVideoStorageSizeToJSONTyped(value?: BunnyVideoStorageSize | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

