/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BunnyVideo } from './BunnyVideo';
import {
    BunnyVideoFromJSON,
    BunnyVideoFromJSONTyped,
    BunnyVideoToJSON,
    BunnyVideoToJSONTyped,
} from './BunnyVideo';

/**
 * 
 * @export
 * @interface Clip
 */
export interface Clip {
    /**
     * 
     * @type {string}
     * @memberof Clip
     */
    clipId: string;
    /**
     * 
     * @type {string}
     * @memberof Clip
     */
    ownerId: string;
    /**
     * 
     * @type {string}
     * @memberof Clip
     */
    videoId: string;
    /**
     * 
     * @type {number}
     * @memberof Clip
     */
    categoryEnum: number;
    /**
     * 
     * @type {BunnyVideo}
     * @memberof Clip
     */
    video: BunnyVideo;
    /**
     * 
     * @type {Array<string>}
     * @memberof Clip
     */
    tags: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Clip
     */
    isViewed: boolean;
}

/**
 * Check if a given object implements the Clip interface.
 */
export function instanceOfClip(value: object): value is Clip {
    if (!('clipId' in value) || value['clipId'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    if (!('categoryEnum' in value) || value['categoryEnum'] === undefined) return false;
    if (!('video' in value) || value['video'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('isViewed' in value) || value['isViewed'] === undefined) return false;
    return true;
}

export function ClipFromJSON(json: any): Clip {
    return ClipFromJSONTyped(json, false);
}

export function ClipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Clip {
    if (json == null) {
        return json;
    }
    return {
        
        'clipId': json['clip_id'],
        'ownerId': json['owner_id'],
        'videoId': json['video_id'],
        'categoryEnum': json['category_enum'],
        'video': BunnyVideoFromJSON(json['video']),
        'tags': json['tags'],
        'isViewed': json['is_viewed'],
    };
}

export function ClipToJSON(json: any): Clip {
    return ClipToJSONTyped(json, false);
}

export function ClipToJSONTyped(value?: Clip | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clip_id': value['clipId'],
        'owner_id': value['ownerId'],
        'video_id': value['videoId'],
        'category_enum': value['categoryEnum'],
        'video': BunnyVideoToJSON(value['video']),
        'tags': value['tags'],
        'is_viewed': value['isViewed'],
    };
}

