"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfClipCategory = instanceOfClipCategory;
exports.ClipCategoryFromJSON = ClipCategoryFromJSON;
exports.ClipCategoryFromJSONTyped = ClipCategoryFromJSONTyped;
exports.ClipCategoryToJSON = ClipCategoryToJSON;
exports.ClipCategoryToJSONTyped = ClipCategoryToJSONTyped;
/**
 * Check if a given object implements the ClipCategory interface.
 */
function instanceOfClipCategory(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('categoryEnum' in value) || value['categoryEnum'] === undefined)
        return false;
    if (!('artUrl' in value) || value['artUrl'] === undefined)
        return false;
    return true;
}
function ClipCategoryFromJSON(json) {
    return ClipCategoryFromJSONTyped(json, false);
}
function ClipCategoryFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'categoryEnum': json['category_enum'],
        'artUrl': json['art_url'],
    };
}
function ClipCategoryToJSON(json) {
    return ClipCategoryToJSONTyped(json, false);
}
function ClipCategoryToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'category_enum': value['categoryEnum'],
        'art_url': value['artUrl'],
    };
}
