/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDirectoryRequest
 */
export interface CreateDirectoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDirectoryRequest
     */
    path: string;
}

/**
 * Check if a given object implements the CreateDirectoryRequest interface.
 */
export function instanceOfCreateDirectoryRequest(value: object): value is CreateDirectoryRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function CreateDirectoryRequestFromJSON(json: any): CreateDirectoryRequest {
    return CreateDirectoryRequestFromJSONTyped(json, false);
}

export function CreateDirectoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDirectoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
    };
}

export function CreateDirectoryRequestToJSON(json: any): CreateDirectoryRequest {
    return CreateDirectoryRequestToJSONTyped(json, false);
}

export function CreateDirectoryRequestToJSONTyped(value?: CreateDirectoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
    };
}

