/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGamingSessionPlaylistRequest
 */
export interface CreateGamingSessionPlaylistRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateGamingSessionPlaylistRequest
     */
    participants: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateGamingSessionPlaylistRequest
     */
    category: number;
}

/**
 * Check if a given object implements the CreateGamingSessionPlaylistRequest interface.
 */
export function instanceOfCreateGamingSessionPlaylistRequest(value: object): value is CreateGamingSessionPlaylistRequest {
    if (!('participants' in value) || value['participants'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function CreateGamingSessionPlaylistRequestFromJSON(json: any): CreateGamingSessionPlaylistRequest {
    return CreateGamingSessionPlaylistRequestFromJSONTyped(json, false);
}

export function CreateGamingSessionPlaylistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGamingSessionPlaylistRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'participants': json['participants'],
        'category': json['category'],
    };
}

export function CreateGamingSessionPlaylistRequestToJSON(json: any): CreateGamingSessionPlaylistRequest {
    return CreateGamingSessionPlaylistRequestToJSONTyped(json, false);
}

export function CreateGamingSessionPlaylistRequestToJSONTyped(value?: CreateGamingSessionPlaylistRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'participants': value['participants'],
        'category': value['category'],
    };
}

