"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCreateClipResponse = instanceOfCreateClipResponse;
exports.CreateClipResponseFromJSON = CreateClipResponseFromJSON;
exports.CreateClipResponseFromJSONTyped = CreateClipResponseFromJSONTyped;
exports.CreateClipResponseToJSON = CreateClipResponseToJSON;
exports.CreateClipResponseToJSONTyped = CreateClipResponseToJSONTyped;
/**
 * Check if a given object implements the CreateClipResponse interface.
 */
function instanceOfCreateClipResponse(value) {
    if (!('signature' in value) || value['signature'] === undefined)
        return false;
    if (!('expiration' in value) || value['expiration'] === undefined)
        return false;
    if (!('libraryId' in value) || value['libraryId'] === undefined)
        return false;
    if (!('videoId' in value) || value['videoId'] === undefined)
        return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined)
        return false;
    return true;
}
function CreateClipResponseFromJSON(json) {
    return CreateClipResponseFromJSONTyped(json, false);
}
function CreateClipResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'signature': json['signature'],
        'expiration': json['expiration'],
        'libraryId': json['library_id'],
        'videoId': json['video_id'],
        'collectionId': json['collection_id'],
    };
}
function CreateClipResponseToJSON(json) {
    return CreateClipResponseToJSONTyped(json, false);
}
function CreateClipResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'signature': value['signature'],
        'expiration': value['expiration'],
        'library_id': value['libraryId'],
        'video_id': value['videoId'],
        'collection_id': value['collectionId'],
    };
}
