/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MapInfo } from './MapInfo';
import {
    MapInfoFromJSON,
    MapInfoFromJSONTyped,
    MapInfoToJSON,
    MapInfoToJSONTyped,
} from './MapInfo';

/**
 * 
 * @export
 * @interface CurrentMapRotation
 */
export interface CurrentMapRotation {
    /**
     * 
     * @type {MapInfo}
     * @memberof CurrentMapRotation
     */
    standardMap: MapInfo;
    /**
     * 
     * @type {MapInfo}
     * @memberof CurrentMapRotation
     */
    standardMapNext: MapInfo;
    /**
     * 
     * @type {MapInfo}
     * @memberof CurrentMapRotation
     */
    rankedMap: MapInfo;
    /**
     * 
     * @type {MapInfo}
     * @memberof CurrentMapRotation
     */
    rankedMapNext: MapInfo;
    /**
     * 
     * @type {Date}
     * @memberof CurrentMapRotation
     */
    correctAsOf: Date;
}

/**
 * Check if a given object implements the CurrentMapRotation interface.
 */
export function instanceOfCurrentMapRotation(value: object): value is CurrentMapRotation {
    if (!('standardMap' in value) || value['standardMap'] === undefined) return false;
    if (!('standardMapNext' in value) || value['standardMapNext'] === undefined) return false;
    if (!('rankedMap' in value) || value['rankedMap'] === undefined) return false;
    if (!('rankedMapNext' in value) || value['rankedMapNext'] === undefined) return false;
    if (!('correctAsOf' in value) || value['correctAsOf'] === undefined) return false;
    return true;
}

export function CurrentMapRotationFromJSON(json: any): CurrentMapRotation {
    return CurrentMapRotationFromJSONTyped(json, false);
}

export function CurrentMapRotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentMapRotation {
    if (json == null) {
        return json;
    }
    return {
        
        'standardMap': MapInfoFromJSON(json['standard_map']),
        'standardMapNext': MapInfoFromJSON(json['standard_map_next']),
        'rankedMap': MapInfoFromJSON(json['ranked_map']),
        'rankedMapNext': MapInfoFromJSON(json['ranked_map_next']),
        'correctAsOf': (new Date(json['correct_as_of'])),
    };
}

export function CurrentMapRotationToJSON(json: any): CurrentMapRotation {
    return CurrentMapRotationToJSONTyped(json, false);
}

export function CurrentMapRotationToJSONTyped(value?: CurrentMapRotation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'standard_map': MapInfoToJSON(value['standardMap']),
        'standard_map_next': MapInfoToJSON(value['standardMapNext']),
        'ranked_map': MapInfoToJSON(value['rankedMap']),
        'ranked_map_next': MapInfoToJSON(value['rankedMapNext']),
        'correct_as_of': value['correctAsOf'].toISOString(),
    };
}

