"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDiscordUser = instanceOfDiscordUser;
exports.DiscordUserFromJSON = DiscordUserFromJSON;
exports.DiscordUserFromJSONTyped = DiscordUserFromJSONTyped;
exports.DiscordUserToJSON = DiscordUserToJSON;
exports.DiscordUserToJSONTyped = DiscordUserToJSONTyped;
/**
 * Check if a given object implements the DiscordUser interface.
 */
function instanceOfDiscordUser(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('username' in value) || value['username'] === undefined)
        return false;
    if (!('avatar' in value) || value['avatar'] === undefined)
        return false;
    return true;
}
function DiscordUserFromJSON(json) {
    return DiscordUserFromJSONTyped(json, false);
}
function DiscordUserFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'username': json['username'],
        'avatar': json['avatar'],
    };
}
function DiscordUserToJSON(json) {
    return DiscordUserToJSONTyped(json, false);
}
function DiscordUserToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'username': value['username'],
        'avatar': value['avatar'],
    };
}
