/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscordUser
 */
export interface DiscordUser {
    /**
     * 
     * @type {string}
     * @memberof DiscordUser
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DiscordUser
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof DiscordUser
     */
    avatar: string | null;
}

/**
 * Check if a given object implements the DiscordUser interface.
 */
export function instanceOfDiscordUser(value: object): value is DiscordUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    return true;
}

export function DiscordUserFromJSON(json: any): DiscordUser {
    return DiscordUserFromJSONTyped(json, false);
}

export function DiscordUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscordUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'avatar': json['avatar'],
    };
}

export function DiscordUserToJSON(json: any): DiscordUser {
    return DiscordUserToJSONTyped(json, false);
}

export function DiscordUserToJSONTyped(value?: DiscordUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'avatar': value['avatar'],
    };
}

