/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameCategoryResponse
 */
export interface GameCategoryResponse {
    /**
     * 
     * @type {string}
     * @memberof GameCategoryResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GameCategoryResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GameCategoryResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof GameCategoryResponse
     */
    coverUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameCategoryResponse
     */
    keyArtUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameCategoryResponse
     */
    gameLogoUrl: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GameCategoryResponse
     */
    isCustom: boolean;
}

/**
 * Check if a given object implements the GameCategoryResponse interface.
 */
export function instanceOfGameCategoryResponse(value: object): value is GameCategoryResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('coverUrl' in value) || value['coverUrl'] === undefined) return false;
    if (!('keyArtUrl' in value) || value['keyArtUrl'] === undefined) return false;
    if (!('gameLogoUrl' in value) || value['gameLogoUrl'] === undefined) return false;
    if (!('isCustom' in value) || value['isCustom'] === undefined) return false;
    return true;
}

export function GameCategoryResponseFromJSON(json: any): GameCategoryResponse {
    return GameCategoryResponseFromJSONTyped(json, false);
}

export function GameCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'coverUrl': json['cover_url'],
        'keyArtUrl': json['key_art_url'],
        'gameLogoUrl': json['game_logo_url'],
        'isCustom': json['is_custom'],
    };
}

export function GameCategoryResponseToJSON(json: any): GameCategoryResponse {
    return GameCategoryResponseToJSONTyped(json, false);
}

export function GameCategoryResponseToJSONTyped(value?: GameCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'cover_url': value['coverUrl'],
        'key_art_url': value['keyArtUrl'],
        'game_logo_url': value['gameLogoUrl'],
        'is_custom': value['isCustom'],
    };
}
