/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkRequest
 */
export interface LinkRequest {
    /**
     * 
     * @type {string}
     * @memberof LinkRequest
     */
    url: string;
}

/**
 * Check if a given object implements the LinkRequest interface.
 */
export function instanceOfLinkRequest(value: object): value is LinkRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function LinkRequestFromJSON(json: any): LinkRequest {
    return LinkRequestFromJSONTyped(json, false);
}

export function LinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function LinkRequestToJSON(json: any): LinkRequest {
    return LinkRequestToJSONTyped(json, false);
}

export function LinkRequestToJSONTyped(value?: LinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

