/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapInfo
 */
export interface MapInfo {
    /**
     * 
     * @type {string}
     * @memberof MapInfo
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof MapInfo
     */
    mapStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof MapInfo
     */
    mapEnd: Date;
    /**
     * 
     * @type {string}
     * @memberof MapInfo
     */
    assetUri: string;
}

/**
 * Check if a given object implements the MapInfo interface.
 */
export function instanceOfMapInfo(value: object): value is MapInfo {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('mapStart' in value) || value['mapStart'] === undefined) return false;
    if (!('mapEnd' in value) || value['mapEnd'] === undefined) return false;
    if (!('assetUri' in value) || value['assetUri'] === undefined) return false;
    return true;
}

export function MapInfoFromJSON(json: any): MapInfo {
    return MapInfoFromJSONTyped(json, false);
}

export function MapInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'mapStart': (new Date(json['map_start'])),
        'mapEnd': (new Date(json['map_end'])),
        'assetUri': json['asset_uri'],
    };
}

export function MapInfoToJSON(json: any): MapInfo {
    return MapInfoToJSONTyped(json, false);
}

export function MapInfoToJSONTyped(value?: MapInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'map_start': value['mapStart'].toISOString(),
        'map_end': value['mapEnd'].toISOString(),
        'asset_uri': value['assetUri'],
    };
}

