"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfMetaTag = instanceOfMetaTag;
exports.MetaTagFromJSON = MetaTagFromJSON;
exports.MetaTagFromJSONTyped = MetaTagFromJSONTyped;
exports.MetaTagToJSON = MetaTagToJSON;
exports.MetaTagToJSONTyped = MetaTagToJSONTyped;
/**
 * Check if a given object implements the MetaTag interface.
 */
function instanceOfMetaTag(value) {
    if (!('property' in value) || value['property'] === undefined)
        return false;
    if (!('value' in value) || value['value'] === undefined)
        return false;
    return true;
}
function MetaTagFromJSON(json) {
    return MetaTagFromJSONTyped(json, false);
}
function MetaTagFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'property': json['property'],
        'value': json['value'],
    };
}
function MetaTagToJSON(json) {
    return MetaTagToJSONTyped(json, false);
}
function MetaTagToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'property': value['property'],
        'value': value['value'],
    };
}
