/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetaTag
 */
export interface MetaTag {
    /**
     * 
     * @type {string}
     * @memberof MetaTag
     */
    property: string;
    /**
     * 
     * @type {string}
     * @memberof MetaTag
     */
    value: string;
}

/**
 * Check if a given object implements the MetaTag interface.
 */
export function instanceOfMetaTag(value: object): value is MetaTag {
    if (!('property' in value) || value['property'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function MetaTagFromJSON(json: any): MetaTag {
    return MetaTagFromJSONTyped(json, false);
}

export function MetaTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaTag {
    if (json == null) {
        return json;
    }
    return {
        
        'property': json['property'],
        'value': json['value'],
    };
}

export function MetaTagToJSON(json: any): MetaTag {
    return MetaTagToJSONTyped(json, false);
}

export function MetaTagToJSONTyped(value?: MetaTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property': value['property'],
        'value': value['value'],
    };
}

