/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MinecraftServer
 */
export interface MinecraftServer {
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    persistenceLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    containerName?: string;
    /**
     * 
     * @type {number}
     * @memberof MinecraftServer
     */
    cpuReservation?: number;
    /**
     * 
     * @type {number}
     * @memberof MinecraftServer
     */
    ramReservation?: number;
    /**
     * 
     * @type {number}
     * @memberof MinecraftServer
     */
    cpuLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof MinecraftServer
     */
    ramLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof MinecraftServer
     */
    serverType?: number;
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    minecraftVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    modloaderVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    curseforgePageUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MinecraftServer
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof MinecraftServer
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    rconPassword?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MinecraftServer
     */
    maxPlayers?: number;
    /**
     * 
     * @type {string}
     * @memberof MinecraftServer
     */
    motd?: string;
}

/**
 * Check if a given object implements the MinecraftServer interface.
 */
export function instanceOfMinecraftServer(value: object): value is MinecraftServer {
    return true;
}

export function MinecraftServerFromJSON(json: any): MinecraftServer {
    return MinecraftServerFromJSONTyped(json, false);
}

export function MinecraftServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinecraftServer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'persistenceLocation': json['persistence_location'] == null ? undefined : json['persistence_location'],
        'containerName': json['container_name'] == null ? undefined : json['container_name'],
        'cpuReservation': json['cpu_reservation'] == null ? undefined : json['cpu_reservation'],
        'ramReservation': json['ram_reservation'] == null ? undefined : json['ram_reservation'],
        'cpuLimit': json['cpu_limit'] == null ? undefined : json['cpu_limit'],
        'ramLimit': json['ram_limit'] == null ? undefined : json['ram_limit'],
        'serverType': json['server_type'] == null ? undefined : json['server_type'],
        'minecraftVersion': json['minecraft_version'] == null ? undefined : json['minecraft_version'],
        'modloaderVersion': json['modloader_version'] == null ? undefined : json['modloader_version'],
        'curseforgePageUrl': json['curseforge_page_url'] == null ? undefined : json['curseforge_page_url'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'rconPassword': json['rcon_password'] == null ? undefined : json['rcon_password'],
        'maxPlayers': json['max_players'] == null ? undefined : json['max_players'],
        'motd': json['motd'] == null ? undefined : json['motd'],
    };
}

export function MinecraftServerToJSON(json: any): MinecraftServer {
    return MinecraftServerToJSONTyped(json, false);
}

export function MinecraftServerToJSONTyped(value?: MinecraftServer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'owner_id': value['ownerId'],
        'persistence_location': value['persistenceLocation'],
        'container_name': value['containerName'],
        'cpu_reservation': value['cpuReservation'],
        'ram_reservation': value['ramReservation'],
        'cpu_limit': value['cpuLimit'],
        'ram_limit': value['ramLimit'],
        'server_type': value['serverType'],
        'minecraft_version': value['minecraftVersion'],
        'modloader_version': value['modloaderVersion'],
        'curseforge_page_url': value['curseforgePageUrl'],
        'is_active': value['isActive'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'rcon_password': value['rconPassword'],
        'max_players': value['maxPlayers'],
        'motd': value['motd'],
    };
}

