/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetVideosByCategoryPageParameter } from './GetVideosByCategoryPageParameter';
import {
    GetVideosByCategoryPageParameterFromJSON,
    GetVideosByCategoryPageParameterFromJSONTyped,
    GetVideosByCategoryPageParameterToJSON,
    GetVideosByCategoryPageParameterToJSONTyped,
} from './GetVideosByCategoryPageParameter';

/**
 * 
 * @export
 * @interface Moment
 */
export interface Moment {
    /**
     * 
     * @type {string}
     * @memberof Moment
     */
    label: string;
    /**
     * 
     * @type {GetVideosByCategoryPageParameter}
     * @memberof Moment
     */
    timestamp: GetVideosByCategoryPageParameter;
}

/**
 * Check if a given object implements the Moment interface.
 */
export function instanceOfMoment(value: object): value is Moment {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function MomentFromJSON(json: any): Moment {
    return MomentFromJSONTyped(json, false);
}

export function MomentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Moment {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'timestamp': GetVideosByCategoryPageParameterFromJSON(json['timestamp']),
    };
}

export function MomentToJSON(json: any): Moment {
    return MomentToJSONTyped(json, false);
}

export function MomentToJSONTyped(value?: Moment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'timestamp': GetVideosByCategoryPageParameterToJSON(value['timestamp']),
    };
}

