"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfMoment = instanceOfMoment;
exports.MomentFromJSON = MomentFromJSON;
exports.MomentFromJSONTyped = MomentFromJSONTyped;
exports.MomentToJSON = MomentToJSON;
exports.MomentToJSONTyped = MomentToJSONTyped;
/**
 * Check if a given object implements the Moment interface.
 */
function instanceOfMoment(value) {
    if (!('label' in value) || value['label'] === undefined)
        return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined)
        return false;
    return true;
}
function MomentFromJSON(json) {
    return MomentFromJSONTyped(json, false);
}
function MomentFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'label': json['label'],
        'timestamp': json['timestamp'],
    };
}
function MomentToJSON(json) {
    return MomentToJSONTyped(json, false);
}
function MomentToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'label': value['label'],
        'timestamp': value['timestamp'],
    };
}
