/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProvisionResponse
 */
export interface ProvisionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ProvisionResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProvisionResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ProvisionResponse
     */
    containerId: string;
    /**
     * 
     * @type {string}
     * @memberof ProvisionResponse
     */
    volumeName: string;
}

/**
 * Check if a given object implements the ProvisionResponse interface.
 */
export function instanceOfProvisionResponse(value: object): value is ProvisionResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('containerId' in value) || value['containerId'] === undefined) return false;
    if (!('volumeName' in value) || value['volumeName'] === undefined) return false;
    return true;
}

export function ProvisionResponseFromJSON(json: any): ProvisionResponse {
    return ProvisionResponseFromJSONTyped(json, false);
}

export function ProvisionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProvisionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'containerId': json['container_id'],
        'volumeName': json['volume_name'],
    };
}

export function ProvisionResponseToJSON(json: any): ProvisionResponse {
    return ProvisionResponseToJSONTyped(json, false);
}

export function ProvisionResponseToJSONTyped(value?: ProvisionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'container_id': value['containerId'],
        'volume_name': value['volumeName'],
    };
}

