/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveFileRequest
 */
export interface SaveFileRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveFileRequest
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof SaveFileRequest
     */
    content: string | null;
}

/**
 * Check if a given object implements the SaveFileRequest interface.
 */
export function instanceOfSaveFileRequest(value: object): value is SaveFileRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SaveFileRequestFromJSON(json: any): SaveFileRequest {
    return SaveFileRequestFromJSONTyped(json, false);
}

export function SaveFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'content': json['content'],
    };
}

export function SaveFileRequestToJSON(json: any): SaveFileRequest {
    return SaveFileRequestToJSONTyped(json, false);
}

export function SaveFileRequestToJSONTyped(value?: SaveFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'content': value['content'],
    };
}

