"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTopTag = instanceOfTopTag;
exports.TopTagFromJSON = TopTagFromJSON;
exports.TopTagFromJSONTyped = TopTagFromJSONTyped;
exports.TopTagToJSON = TopTagToJSON;
exports.TopTagToJSONTyped = TopTagToJSONTyped;
/**
 * Check if a given object implements the TopTag interface.
 */
function instanceOfTopTag(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('count' in value) || value['count'] === undefined)
        return false;
    return true;
}
function TopTagFromJSON(json) {
    return TopTagFromJSONTyped(json, false);
}
function TopTagFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'count': json['count'],
    };
}
function TopTagToJSON(json) {
    return TopTagToJSONTyped(json, false);
}
function TopTagToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'count': value['count'],
    };
}
