/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTitleRequest
 */
export interface UpdateTitleRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTitleRequest
     */
    title: string;
}

/**
 * Check if a given object implements the UpdateTitleRequest interface.
 */
export function instanceOfUpdateTitleRequest(value: object): value is UpdateTitleRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function UpdateTitleRequestFromJSON(json: any): UpdateTitleRequest {
    return UpdateTitleRequestFromJSONTyped(json, false);
}

export function UpdateTitleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTitleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function UpdateTitleRequestToJSON(json: any): UpdateTitleRequest {
    return UpdateTitleRequestToJSONTyped(json, false);
}

export function UpdateTitleRequestToJSONTyped(value?: UpdateTitleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
    };
}

