"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUpdateTitleRequest = instanceOfUpdateTitleRequest;
exports.UpdateTitleRequestFromJSON = UpdateTitleRequestFromJSON;
exports.UpdateTitleRequestFromJSONTyped = UpdateTitleRequestFromJSONTyped;
exports.UpdateTitleRequestToJSON = UpdateTitleRequestToJSON;
exports.UpdateTitleRequestToJSONTyped = UpdateTitleRequestToJSONTyped;
/**
 * Check if a given object implements the UpdateTitleRequest interface.
 */
function instanceOfUpdateTitleRequest(value) {
    if (!('title' in value) || value['title'] === undefined)
        return false;
    return true;
}
function UpdateTitleRequestFromJSON(json) {
    return UpdateTitleRequestFromJSONTyped(json, false);
}
function UpdateTitleRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'title': json['title'],
    };
}
function UpdateTitleRequestToJSON(json) {
    return UpdateTitleRequestToJSONTyped(json, false);
}
function UpdateTitleRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'title': value['title'],
    };
}
