/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePreferencesRequest
 */
export interface UpdatePreferencesRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePreferencesRequest
     */
    discordNotificationsEnabled: boolean;
}

/**
 * Check if a given object implements the UpdatePreferencesRequest interface.
 */
export function instanceOfUpdatePreferencesRequest(value: object): value is UpdatePreferencesRequest {
    if (!('discordNotificationsEnabled' in value) || value['discordNotificationsEnabled'] === undefined) return false;
    return true;
}

export function UpdatePreferencesRequestFromJSON(json: any): UpdatePreferencesRequest {
    return UpdatePreferencesRequestFromJSONTyped(json, false);
}

export function UpdatePreferencesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePreferencesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'discordNotificationsEnabled': json['discord_notifications_enabled'],
    };
}

export function UpdatePreferencesRequestToJSON(json: any): UpdatePreferencesRequest {
    return UpdatePreferencesRequestToJSONTyped(json, false);
}

export function UpdatePreferencesRequestToJSONTyped(value?: UpdatePreferencesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'discord_notifications_enabled': value['discordNotificationsEnabled'],
    };
}

