/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPreferences
 */
export interface UserPreferences {
    /**
     * 
     * @type {boolean}
     * @memberof UserPreferences
     */
    discordNotificationsEnabled?: boolean;
}

/**
 * Check if a given object implements the UserPreferences interface.
 */
export function instanceOfUserPreferences(value: object): value is UserPreferences {
    return true;
}

export function UserPreferencesFromJSON(json: any): UserPreferences {
    return UserPreferencesFromJSONTyped(json, false);
}

export function UserPreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPreferences {
    if (json == null) {
        return json;
    }
    return {
        
        'discordNotificationsEnabled': json['discord_notifications_enabled'] == null ? undefined : json['discord_notifications_enabled'],
    };
}

export function UserPreferencesToJSON(json: any): UserPreferences {
    return UserPreferencesToJSONTyped(json, false);
}

export function UserPreferencesToJSONTyped(value?: UserPreferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'discord_notifications_enabled': value['discordNotificationsEnabled'],
    };
}

