/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserFrequentLink
 */
export interface UserFrequentLink {
    /**
     * 
     * @type {string}
     * @memberof UserFrequentLink
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFrequentLink
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFrequentLink
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFrequentLink
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof UserFrequentLink
     */
    thumbnailUrl?: string | null;
}

/**
 * Check if a given object implements the UserFrequentLink interface.
 */
export function instanceOfUserFrequentLink(value: object): value is UserFrequentLink {
    return true;
}

export function UserFrequentLinkFromJSON(json: any): UserFrequentLink {
    return UserFrequentLinkFromJSONTyped(json, false);
}

export function UserFrequentLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFrequentLink {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'] == null ? undefined : json['url'],
        'thumbnailUrl': json['thumbnail_url'] == null ? undefined : json['thumbnail_url'],
    };
}

export function UserFrequentLinkToJSON(json: any): UserFrequentLink {
    return UserFrequentLinkToJSONTyped(json, false);
}

export function UserFrequentLinkToJSONTyped(value?: UserFrequentLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'title': value['title'],
        'url': value['url'],
        'thumbnail_url': value['thumbnailUrl'],
    };
}

