/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoProgressUpdate
 */
export interface VideoProgressUpdate {
    /**
     * 
     * @type {number}
     * @memberof VideoProgressUpdate
     */
    videoLibraryId: number;
    /**
     * 
     * @type {string}
     * @memberof VideoProgressUpdate
     */
    videoGuid: string;
    /**
     * 
     * @type {number}
     * @memberof VideoProgressUpdate
     */
    status: number;
}

/**
 * Check if a given object implements the VideoProgressUpdate interface.
 */
export function instanceOfVideoProgressUpdate(value: object): value is VideoProgressUpdate {
    if (!('videoLibraryId' in value) || value['videoLibraryId'] === undefined) return false;
    if (!('videoGuid' in value) || value['videoGuid'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function VideoProgressUpdateFromJSON(json: any): VideoProgressUpdate {
    return VideoProgressUpdateFromJSONTyped(json, false);
}

export function VideoProgressUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoProgressUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'videoLibraryId': json['VideoLibraryId'],
        'videoGuid': json['VideoGuid'],
        'status': json['Status'],
    };
}

export function VideoProgressUpdateToJSON(json: any): VideoProgressUpdate {
    return VideoProgressUpdateToJSONTyped(json, false);
}

export function VideoProgressUpdateToJSONTyped(value?: VideoProgressUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'VideoLibraryId': value['videoLibraryId'],
        'VideoGuid': value['videoGuid'],
        'Status': value['status'],
    };
}

