/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Minecraft | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BackupListResult,
  BackupSyncResult,
  CommandLogEntry,
  ContainerActionResponse,
  ContainerStateResponse,
  CreateDirectoryRequest,
  CreateMinecraftServerRequest,
  DirectoryListing,
  MinecraftServer,
  OnlinePlayer,
  ProvisionResponse,
  RconCommand,
  RconResponse,
  SaveFileRequest,
  ServerStatus,
  UpdateMinecraftServerRequest,
} from '../models/index';
import {
    BackupListResultFromJSON,
    BackupListResultToJSON,
    BackupSyncResultFromJSON,
    BackupSyncResultToJSON,
    CommandLogEntryFromJSON,
    CommandLogEntryToJSON,
    ContainerActionResponseFromJSON,
    ContainerActionResponseToJSON,
    ContainerStateResponseFromJSON,
    ContainerStateResponseToJSON,
    CreateDirectoryRequestFromJSON,
    CreateDirectoryRequestToJSON,
    CreateMinecraftServerRequestFromJSON,
    CreateMinecraftServerRequestToJSON,
    DirectoryListingFromJSON,
    DirectoryListingToJSON,
    MinecraftServerFromJSON,
    MinecraftServerToJSON,
    OnlinePlayerFromJSON,
    OnlinePlayerToJSON,
    ProvisionResponseFromJSON,
    ProvisionResponseToJSON,
    RconCommandFromJSON,
    RconCommandToJSON,
    RconResponseFromJSON,
    RconResponseToJSON,
    SaveFileRequestFromJSON,
    SaveFileRequestToJSON,
    ServerStatusFromJSON,
    ServerStatusToJSON,
    UpdateMinecraftServerRequestFromJSON,
    UpdateMinecraftServerRequestToJSON,
} from '../models/index';

export interface ConsoleWebSocketRequest {
    serverId: string;
}

export interface CreateMinecraftDirectoryRequest {
    serverId: string;
    createDirectoryRequest: CreateDirectoryRequest;
}

export interface CreateMinecraftServerOperationRequest {
    createMinecraftServerRequest: CreateMinecraftServerRequest;
}

export interface DeleteMinecraftFileRequest {
    serverId: string;
    path: string;
}

export interface DeleteMinecraftServerRequest {
    serverId: string;
}

export interface DestroyContainerRequest {
    serverId: string;
    removeData?: boolean;
}

export interface GetBackupStatusRequest {
    serverId: string;
}

export interface GetCommandHistoryRequest {
    serverId: string;
    limit?: number;
}

export interface GetContainerStateRequest {
    serverId: string;
}

export interface GetMinecraftFileContentRequest {
    serverId: string;
    path: string;
}

export interface GetMinecraftPlayersRequest {
    serverId: string;
}

export interface GetMinecraftServerRequest {
    serverId: string;
}

export interface GetMinecraftStatusRequest {
    serverId: string;
}

export interface ListMinecraftFilesRequest {
    serverId: string;
    path?: string;
}

export interface ProvisionContainerRequest {
    serverId: string;
}

export interface SaveMinecraftFileContentRequest {
    serverId: string;
    saveFileRequest: SaveFileRequest;
}

export interface SendMinecraftCommandRequest {
    serverId: string;
    rconCommand: RconCommand;
}

export interface StartContainerRequest {
    serverId: string;
}

export interface StopContainerRequest {
    serverId: string;
    timeout?: number;
    announce?: boolean;
}

export interface TriggerBackupSyncRequest {
    serverId: string;
}

export interface UpdateMinecraftServerOperationRequest {
    serverId: string;
    updateMinecraftServerRequest: UpdateMinecraftServerRequest;
}

/**
 * 
 */
export class MinecraftEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async consoleWebSocketRaw(requestParameters: ConsoleWebSocketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling consoleWebSocket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/console/live`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async consoleWebSocket(requestParameters: ConsoleWebSocketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.consoleWebSocketRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createMinecraftDirectoryRaw(requestParameters: CreateMinecraftDirectoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling createMinecraftDirectory().'
            );
        }

        if (requestParameters['createDirectoryRequest'] == null) {
            throw new runtime.RequiredError(
                'createDirectoryRequest',
                'Required parameter "createDirectoryRequest" was null or undefined when calling createMinecraftDirectory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/minecraft/servers/{serverId}/files/mkdir`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDirectoryRequestToJSON(requestParameters['createDirectoryRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createMinecraftDirectory(requestParameters: CreateMinecraftDirectoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createMinecraftDirectoryRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createMinecraftServerRaw(requestParameters: CreateMinecraftServerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MinecraftServer>> {
        if (requestParameters['createMinecraftServerRequest'] == null) {
            throw new runtime.RequiredError(
                'createMinecraftServerRequest',
                'Required parameter "createMinecraftServerRequest" was null or undefined when calling createMinecraftServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/minecraft/servers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMinecraftServerRequestToJSON(requestParameters['createMinecraftServerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MinecraftServerFromJSON(jsonValue));
    }

    /**
     */
    async createMinecraftServer(requestParameters: CreateMinecraftServerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MinecraftServer> {
        const response = await this.createMinecraftServerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteMinecraftFileRaw(requestParameters: DeleteMinecraftFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling deleteMinecraftFile().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling deleteMinecraftFile().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/files`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteMinecraftFile(requestParameters: DeleteMinecraftFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMinecraftFileRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteMinecraftServerRaw(requestParameters: DeleteMinecraftServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling deleteMinecraftServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteMinecraftServer(requestParameters: DeleteMinecraftServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMinecraftServerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async destroyContainerRaw(requestParameters: DestroyContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContainerActionResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling destroyContainer().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['removeData'] != null) {
            queryParameters['removeData'] = requestParameters['removeData'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/container`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerActionResponseFromJSON(jsonValue));
    }

    /**
     */
    async destroyContainer(requestParameters: DestroyContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContainerActionResponse> {
        const response = await this.destroyContainerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getBackupStatusRaw(requestParameters: GetBackupStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupListResult>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling getBackupStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/backups`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupListResultFromJSON(jsonValue));
    }

    /**
     */
    async getBackupStatus(requestParameters: GetBackupStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupListResult> {
        const response = await this.getBackupStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCommandHistoryRaw(requestParameters: GetCommandHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommandLogEntry>>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling getCommandHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/console/history`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommandLogEntryFromJSON));
    }

    /**
     */
    async getCommandHistory(requestParameters: GetCommandHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommandLogEntry>> {
        const response = await this.getCommandHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getContainerStateRaw(requestParameters: GetContainerStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContainerStateResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling getContainerState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/container`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerStateResponseFromJSON(jsonValue));
    }

    /**
     */
    async getContainerState(requestParameters: GetContainerStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContainerStateResponse> {
        const response = await this.getContainerStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMinecraftFileContentRaw(requestParameters: GetMinecraftFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling getMinecraftFileContent().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling getMinecraftFileContent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/files/content`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getMinecraftFileContent(requestParameters: GetMinecraftFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getMinecraftFileContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMinecraftPlayersRaw(requestParameters: GetMinecraftPlayersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OnlinePlayer>>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling getMinecraftPlayers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/players`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OnlinePlayerFromJSON));
    }

    /**
     */
    async getMinecraftPlayers(requestParameters: GetMinecraftPlayersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OnlinePlayer>> {
        const response = await this.getMinecraftPlayersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMinecraftServerRaw(requestParameters: GetMinecraftServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MinecraftServer>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling getMinecraftServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MinecraftServerFromJSON(jsonValue));
    }

    /**
     */
    async getMinecraftServer(requestParameters: GetMinecraftServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MinecraftServer> {
        const response = await this.getMinecraftServerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMinecraftServersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MinecraftServer>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MinecraftServerFromJSON));
    }

    /**
     */
    async getMinecraftServers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MinecraftServer>> {
        const response = await this.getMinecraftServersRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getMinecraftStatusRaw(requestParameters: GetMinecraftStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServerStatus>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling getMinecraftStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/status`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerStatusFromJSON(jsonValue));
    }

    /**
     */
    async getMinecraftStatus(requestParameters: GetMinecraftStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServerStatus> {
        const response = await this.getMinecraftStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listMinecraftFilesRaw(requestParameters: ListMinecraftFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DirectoryListing>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling listMinecraftFiles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/files`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DirectoryListingFromJSON(jsonValue));
    }

    /**
     */
    async listMinecraftFiles(requestParameters: ListMinecraftFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DirectoryListing> {
        const response = await this.listMinecraftFilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async provisionContainerRaw(requestParameters: ProvisionContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProvisionResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling provisionContainer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/container/provision`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProvisionResponseFromJSON(jsonValue));
    }

    /**
     */
    async provisionContainer(requestParameters: ProvisionContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProvisionResponse> {
        const response = await this.provisionContainerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async saveMinecraftFileContentRaw(requestParameters: SaveMinecraftFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling saveMinecraftFileContent().'
            );
        }

        if (requestParameters['saveFileRequest'] == null) {
            throw new runtime.RequiredError(
                'saveFileRequest',
                'Required parameter "saveFileRequest" was null or undefined when calling saveMinecraftFileContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/minecraft/servers/{serverId}/files/content`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SaveFileRequestToJSON(requestParameters['saveFileRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async saveMinecraftFileContent(requestParameters: SaveMinecraftFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.saveMinecraftFileContentRaw(requestParameters, initOverrides);
    }

    /**
     */
    async sendMinecraftCommandRaw(requestParameters: SendMinecraftCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RconResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling sendMinecraftCommand().'
            );
        }

        if (requestParameters['rconCommand'] == null) {
            throw new runtime.RequiredError(
                'rconCommand',
                'Required parameter "rconCommand" was null or undefined when calling sendMinecraftCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/minecraft/servers/{serverId}/console/command`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RconCommandToJSON(requestParameters['rconCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RconResponseFromJSON(jsonValue));
    }

    /**
     */
    async sendMinecraftCommand(requestParameters: SendMinecraftCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RconResponse> {
        const response = await this.sendMinecraftCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async startContainerRaw(requestParameters: StartContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContainerActionResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling startContainer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/container/start`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerActionResponseFromJSON(jsonValue));
    }

    /**
     */
    async startContainer(requestParameters: StartContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContainerActionResponse> {
        const response = await this.startContainerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async stopContainerRaw(requestParameters: StopContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContainerActionResponse>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling stopContainer().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeout'] != null) {
            queryParameters['timeout'] = requestParameters['timeout'];
        }

        if (requestParameters['announce'] != null) {
            queryParameters['announce'] = requestParameters['announce'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/container/stop`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerActionResponseFromJSON(jsonValue));
    }

    /**
     */
    async stopContainer(requestParameters: StopContainerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContainerActionResponse> {
        const response = await this.stopContainerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async triggerBackupSyncRaw(requestParameters: TriggerBackupSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupSyncResult>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling triggerBackupSync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/minecraft/servers/{serverId}/backups/sync`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupSyncResultFromJSON(jsonValue));
    }

    /**
     */
    async triggerBackupSync(requestParameters: TriggerBackupSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupSyncResult> {
        const response = await this.triggerBackupSyncRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateMinecraftServerRaw(requestParameters: UpdateMinecraftServerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MinecraftServer>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling updateMinecraftServer().'
            );
        }

        if (requestParameters['updateMinecraftServerRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMinecraftServerRequest',
                'Required parameter "updateMinecraftServerRequest" was null or undefined when calling updateMinecraftServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/minecraft/servers/{serverId}`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMinecraftServerRequestToJSON(requestParameters['updateMinecraftServerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MinecraftServerFromJSON(jsonValue));
    }

    /**
     */
    async updateMinecraftServer(requestParameters: UpdateMinecraftServerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MinecraftServer> {
        const response = await this.updateMinecraftServerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
