using Reelshelf.Core;
using Reelshelf.Core.Models;
using Reelshelf.Discord;
using Reelshelf.Exceptions;
using Reelshelf.Games;
using Reelshelf.Playlists.Models;

namespace Reelshelf.Playlists;

public class AutoGeneratedGamingSessionPlaylistService(
    IGamingSessionPlaylistStore store)
{
    public async Task<PlaylistWithDetails> EnsureGamingSessionPlaylist(
        Guid categoryId,
        DateOnly sessionDate,
        List<Guid> clipIds,
        string timezone,
        string discordUserId)
    {
        if (string.IsNullOrWhiteSpace(timezone))
        {
            throw new BadRequestException("Timezone is required");
        }

        if (clipIds.Count == 0)
        {
            throw new BadRequestException("At least one clip is required");
        }

        DiscordStatements.DiscordUserRow user = await store.GetUser(discordUserId);
        GameCategory category = await store.GetCategory(categoryId)
                                ?? throw new BadRequestException("Category not found");

        List<Guid> distinctClipIds = clipIds.Distinct().ToList();
        foreach (Guid clipId in distinctClipIds)
        {
            ClipsStatements.ClipRow clip = await store.GetClip(clipId)
                                           ?? throw new BadRequestException($"Clip {clipId} not found");

            if (clip.OwnerId != user.Id)
            {
                throw new BadRequestException($"Clip {clipId} does not belong to the current user");
            }

            if (clip.GameCategoryId != categoryId)
            {
                throw new BadRequestException($"Clip {clipId} does not belong to the requested category");
            }
        }

        Guid playlistId = await EnsureSessionIdentity(category, user, sessionDate, timezone, discordUserId);
        await EnsureClipsPresent(playlistId, distinctClipIds, user.Id);

        return await store.GetPlaylistDetails(playlistId, discordUserId)
               ?? throw new InvalidOperationException("Failed to retrieve gaming session playlist");
    }

    private async Task<Guid> EnsureSessionIdentity(
        GameCategory category,
        DiscordStatements.DiscordUserRow user,
        DateOnly sessionDate,
        string timezone,
        string discordUserId)
    {
        GamingSessionPlaylistRow? existing =
            await store.GetGamingSessionPlaylist(user.Id, category.Id, sessionDate);
        if (existing is not null)
        {
            await store.UpdateGamingSessionTimezone(existing.PlaylistId, timezone);
            return existing.PlaylistId;
        }

        string playlistName = BuildGeneratedName(category.Name, sessionDate);
        Playlist playlist = await store.CreatePlaylist(playlistName, string.Empty, discordUserId);
        Guid sessionPlaylistId = await store.UpsertGamingSessionPlaylist(
            playlist.Id,
            user.Id,
            category.Id,
            sessionDate,
            timezone);

        if (sessionPlaylistId != playlist.Id)
        {
            await store.DeletePlaylist(playlist.Id);
        }

        return sessionPlaylistId;
    }

    private async Task EnsureClipsPresent(Guid playlistId, List<Guid> clipIds, Guid addedByUserId)
    {
        int currentPosition = await store.GetMaxPosition(playlistId) + 1;

        foreach (Guid clipId in clipIds)
        {
            bool exists = await store.ClipExistsInPlaylist(playlistId, clipId);
            if (exists)
            {
                continue;
            }

            await store.AddClipToPlaylist(playlistId, clipId, addedByUserId, currentPosition);
            currentPosition++;
        }

        await store.TouchPlaylistUpdatedAt(playlistId);
    }

    private static string BuildGeneratedName(string categoryName, DateOnly sessionDate)
    {
        return $"{categoryName} · {sessionDate:MMMM d, yyyy}";
    }
}

public interface IGamingSessionPlaylistStore
{
    Task<DiscordStatements.DiscordUserRow> GetUser(string discordUserId);
    Task<GameCategory?> GetCategory(Guid categoryId);
    Task<ClipsStatements.ClipRow?> GetClip(Guid clipId);
    Task<GamingSessionPlaylistRow?> GetGamingSessionPlaylist(Guid ownerId, Guid categoryId, DateOnly sessionDate);
    Task UpdateGamingSessionTimezone(Guid playlistId, string timezone);
    Task<Playlist> CreatePlaylist(string name, string? description, string discordUserId);
    Task<Guid> UpsertGamingSessionPlaylist(Guid playlistId, Guid ownerId, Guid categoryId, DateOnly sessionDate, string timezone);
    Task DeletePlaylist(Guid playlistId);
    Task<int> GetMaxPosition(Guid playlistId);
    Task<bool> ClipExistsInPlaylist(Guid playlistId, Guid clipId);
    Task AddClipToPlaylist(Guid playlistId, Guid clipId, Guid addedByUserId, int position);
    Task TouchPlaylistUpdatedAt(Guid playlistId);
    Task<PlaylistWithDetails?> GetPlaylistDetails(Guid playlistId, string discordUserId);
}

public sealed record GamingSessionPlaylistRow(
    Guid PlaylistId,
    Guid OwnerId,
    Guid GameCategoryId,
    DateOnly SessionDate,
    string Timezone);

