/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Clips | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddTagRequest,
  BackfillResult,
  Clip,
  CreateClipResponse,
  PagedClipsResponse,
  TopTag,
  UpdateTitleRequest,
} from '../models/index';
import {
    AddTagRequestFromJSON,
    AddTagRequestToJSON,
    BackfillResultFromJSON,
    BackfillResultToJSON,
    ClipFromJSON,
    ClipToJSON,
    CreateClipResponseFromJSON,
    CreateClipResponseToJSON,
    PagedClipsResponseFromJSON,
    PagedClipsResponseToJSON,
    TopTagFromJSON,
    TopTagToJSON,
    UpdateTitleRequestFromJSON,
    UpdateTitleRequestToJSON,
} from '../models/index';

export interface AddTagToClipRequest {
    clipId: string;
    addTagRequest: AddTagRequest;
}

export interface CreateVideoRequest {
    categoryId: string;
    videoTitle: string;
    createdAt?: Date;
    md5Hash?: string;
}

export interface DeleteClipRequest {
    clipId: string;
}

export interface GetVideoByIdRequest {
    clipId: string;
}

export interface GetVideosByCategoryRequest {
    categoryId: string;
    page: number;
    pageSize: number;
    tags?: Array<string>;
    titleSearch?: string;
    unviewedOnly?: boolean;
    sortOrder?: number;
    startDate?: Date;
    endDate?: Date;
}

export interface MarkVideoAsViewedRequest {
    clipId: string;
}

export interface RemoveTagFromClipRequest {
    clipId: string;
    tag: string;
}

export interface UpdateClipTitleRequest {
    clipId: string;
    updateTitleRequest: UpdateTitleRequest;
}

/**
 * 
 */
export class ClipsEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async addTagToClipRaw(requestParameters: AddTagToClipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Clip>> {
        if (requestParameters['clipId'] == null) {
            throw new runtime.RequiredError(
                'clipId',
                'Required parameter "clipId" was null or undefined when calling addTagToClip().'
            );
        }

        if (requestParameters['addTagRequest'] == null) {
            throw new runtime.RequiredError(
                'addTagRequest',
                'Required parameter "addTagRequest" was null or undefined when calling addTagToClip().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/clips/videos/{clipId}/tags`;
        urlPath = urlPath.replace(`{${"clipId"}}`, encodeURIComponent(String(requestParameters['clipId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddTagRequestToJSON(requestParameters['addTagRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClipFromJSON(jsonValue));
    }

    /**
     */
    async addTagToClip(requestParameters: AddTagToClipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Clip> {
        const response = await this.addTagToClipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async backfillClipMetadataRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackfillResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/clips/backfill-metadata`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackfillResultFromJSON(jsonValue));
    }

    /**
     */
    async backfillClipMetadata(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackfillResult> {
        const response = await this.backfillClipMetadataRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async createVideoRaw(requestParameters: CreateVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateClipResponse>> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling createVideo().'
            );
        }

        if (requestParameters['videoTitle'] == null) {
            throw new runtime.RequiredError(
                'videoTitle',
                'Required parameter "videoTitle" was null or undefined when calling createVideo().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['videoTitle'] != null) {
            queryParameters['videoTitle'] = requestParameters['videoTitle'];
        }

        if (requestParameters['createdAt'] != null) {
            queryParameters['createdAt'] = requestParameters['createdAt'];
        }

        if (requestParameters['md5Hash'] != null) {
            queryParameters['md5Hash'] = requestParameters['md5Hash'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/clips/categories/{categoryId}/videos`;
        urlPath = urlPath.replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateClipResponseFromJSON(jsonValue));
    }

    /**
     */
    async createVideo(requestParameters: CreateVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateClipResponse> {
        const response = await this.createVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteClipRaw(requestParameters: DeleteClipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['clipId'] == null) {
            throw new runtime.RequiredError(
                'clipId',
                'Required parameter "clipId" was null or undefined when calling deleteClip().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/clips/videos/{clipId}`;
        urlPath = urlPath.replace(`{${"clipId"}}`, encodeURIComponent(String(requestParameters['clipId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteClip(requestParameters: DeleteClipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteClipRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getTopTagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TopTag>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/clips/tags/top`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TopTagFromJSON));
    }

    /**
     */
    async getTopTags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TopTag>> {
        const response = await this.getTopTagsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getVideoByIdRaw(requestParameters: GetVideoByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Clip>> {
        if (requestParameters['clipId'] == null) {
            throw new runtime.RequiredError(
                'clipId',
                'Required parameter "clipId" was null or undefined when calling getVideoById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/clips/videos/{clipId}`;
        urlPath = urlPath.replace(`{${"clipId"}}`, encodeURIComponent(String(requestParameters['clipId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClipFromJSON(jsonValue));
    }

    /**
     */
    async getVideoById(requestParameters: GetVideoByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Clip> {
        const response = await this.getVideoByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getVideosByCategoryRaw(requestParameters: GetVideosByCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedClipsResponse>> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling getVideosByCategory().'
            );
        }

        if (requestParameters['page'] == null) {
            throw new runtime.RequiredError(
                'page',
                'Required parameter "page" was null or undefined when calling getVideosByCategory().'
            );
        }

        if (requestParameters['pageSize'] == null) {
            throw new runtime.RequiredError(
                'pageSize',
                'Required parameter "pageSize" was null or undefined when calling getVideosByCategory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        if (requestParameters['titleSearch'] != null) {
            queryParameters['titleSearch'] = requestParameters['titleSearch'];
        }

        if (requestParameters['unviewedOnly'] != null) {
            queryParameters['unviewedOnly'] = requestParameters['unviewedOnly'];
        }

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sortOrder'] = requestParameters['sortOrder'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = requestParameters['startDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/clips/categories/{categoryId}/videos`;
        urlPath = urlPath.replace(`{${"categoryId"}}`, encodeURIComponent(String(requestParameters['categoryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedClipsResponseFromJSON(jsonValue));
    }

    /**
     */
    async getVideosByCategory(requestParameters: GetVideosByCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedClipsResponse> {
        const response = await this.getVideosByCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async markVideoAsViewedRaw(requestParameters: MarkVideoAsViewedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['clipId'] == null) {
            throw new runtime.RequiredError(
                'clipId',
                'Required parameter "clipId" was null or undefined when calling markVideoAsViewed().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/clips/videos/{clipId}/view`;
        urlPath = urlPath.replace(`{${"clipId"}}`, encodeURIComponent(String(requestParameters['clipId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async markVideoAsViewed(requestParameters: MarkVideoAsViewedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.markVideoAsViewedRaw(requestParameters, initOverrides);
    }

    /**
     */
    async removeTagFromClipRaw(requestParameters: RemoveTagFromClipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Clip>> {
        if (requestParameters['clipId'] == null) {
            throw new runtime.RequiredError(
                'clipId',
                'Required parameter "clipId" was null or undefined when calling removeTagFromClip().'
            );
        }

        if (requestParameters['tag'] == null) {
            throw new runtime.RequiredError(
                'tag',
                'Required parameter "tag" was null or undefined when calling removeTagFromClip().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/clips/videos/{clipId}/tags/{tag}`;
        urlPath = urlPath.replace(`{${"clipId"}}`, encodeURIComponent(String(requestParameters['clipId'])));
        urlPath = urlPath.replace(`{${"tag"}}`, encodeURIComponent(String(requestParameters['tag'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClipFromJSON(jsonValue));
    }

    /**
     */
    async removeTagFromClip(requestParameters: RemoveTagFromClipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Clip> {
        const response = await this.removeTagFromClipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateClipTitleRaw(requestParameters: UpdateClipTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Clip>> {
        if (requestParameters['clipId'] == null) {
            throw new runtime.RequiredError(
                'clipId',
                'Required parameter "clipId" was null or undefined when calling updateClipTitle().'
            );
        }

        if (requestParameters['updateTitleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTitleRequest',
                'Required parameter "updateTitleRequest" was null or undefined when calling updateClipTitle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/clips/videos/{clipId}/title`;
        urlPath = urlPath.replace(`{${"clipId"}}`, encodeURIComponent(String(requestParameters['clipId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTitleRequestToJSON(requestParameters['updateTitleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClipFromJSON(jsonValue));
    }

    /**
     */
    async updateClipTitle(requestParameters: UpdateClipTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Clip> {
        const response = await this.updateClipTitleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
