/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Minecraft | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackupFileInfo
 */
export interface BackupFileInfo {
    /**
     * 
     * @type {string}
     * @memberof BackupFileInfo
     */
    path: string;
    /**
     * 
     * @type {number}
     * @memberof BackupFileInfo
     */
    size: number;
    /**
     * 
     * @type {Date}
     * @memberof BackupFileInfo
     */
    lastModified: Date;
}

/**
 * Check if a given object implements the BackupFileInfo interface.
 */
export function instanceOfBackupFileInfo(value: object): value is BackupFileInfo {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('lastModified' in value) || value['lastModified'] === undefined) return false;
    return true;
}

export function BackupFileInfoFromJSON(json: any): BackupFileInfo {
    return BackupFileInfoFromJSONTyped(json, false);
}

export function BackupFileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupFileInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'size': json['size'],
        'lastModified': (new Date(json['last_modified'])),
    };
}

export function BackupFileInfoToJSON(json: any): BackupFileInfo {
    return BackupFileInfoToJSONTyped(json, false);
}

export function BackupFileInfoToJSONTyped(value?: BackupFileInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'size': value['size'],
        'last_modified': value['lastModified'].toISOString(),
    };
}

