/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Minecraft | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileEntry } from './FileEntry';
import {
    FileEntryFromJSON,
    FileEntryFromJSONTyped,
    FileEntryToJSON,
    FileEntryToJSONTyped,
} from './FileEntry';

/**
 * 
 * @export
 * @interface DirectoryListing
 */
export interface DirectoryListing {
    /**
     * 
     * @type {string}
     * @memberof DirectoryListing
     */
    currentPath: string;
    /**
     * 
     * @type {Array<FileEntry>}
     * @memberof DirectoryListing
     */
    entries: Array<FileEntry>;
}

/**
 * Check if a given object implements the DirectoryListing interface.
 */
export function instanceOfDirectoryListing(value: object): value is DirectoryListing {
    if (!('currentPath' in value) || value['currentPath'] === undefined) return false;
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function DirectoryListingFromJSON(json: any): DirectoryListing {
    return DirectoryListingFromJSONTyped(json, false);
}

export function DirectoryListingFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectoryListing {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPath': json['current_path'],
        'entries': ((json['entries'] as Array<any>).map(FileEntryFromJSON)),
    };
}

export function DirectoryListingToJSON(json: any): DirectoryListing {
    return DirectoryListingToJSONTyped(json, false);
}

export function DirectoryListingToJSONTyped(value?: DirectoryListing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_path': value['currentPath'],
        'entries': ((value['entries'] as Array<any>).map(FileEntryToJSON)),
    };
}

