/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Minecraft | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RconResponse
 */
export interface RconResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RconResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof RconResponse
     */
    response: string | null;
    /**
     * 
     * @type {string}
     * @memberof RconResponse
     */
    error: string | null;
}

/**
 * Check if a given object implements the RconResponse interface.
 */
export function instanceOfRconResponse(value: object): value is RconResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function RconResponseFromJSON(json: any): RconResponse {
    return RconResponseFromJSONTyped(json, false);
}

export function RconResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RconResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'response': json['response'],
        'error': json['error'],
    };
}

export function RconResponseToJSON(json: any): RconResponse {
    return RconResponseToJSONTyped(json, false);
}

export function RconResponseToJSONTyped(value?: RconResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'response': value['response'],
        'error': value['error'],
    };
}

