/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Minecraft | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RconCommand
 */
export interface RconCommand {
    /**
     * 
     * @type {string}
     * @memberof RconCommand
     */
    command: string;
}

/**
 * Check if a given object implements the RconCommand interface.
 */
export function instanceOfRconCommand(value: object): value is RconCommand {
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function RconCommandFromJSON(json: any): RconCommand {
    return RconCommandFromJSONTyped(json, false);
}

export function RconCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): RconCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'],
    };
}

export function RconCommandToJSON(json: any): RconCommand {
    return RconCommandToJSONTyped(json, false);
}

export function RconCommandToJSONTyped(value?: RconCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
    };
}

