/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Clips | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateClipResponse
 */
export interface CreateClipResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateClipResponse
     */
    signature: string;
    /**
     * 
     * @type {number}
     * @memberof CreateClipResponse
     */
    expiration: number;
    /**
     * 
     * @type {string}
     * @memberof CreateClipResponse
     */
    libraryId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateClipResponse
     */
    videoId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateClipResponse
     */
    collectionId: string;
}

/**
 * Check if a given object implements the CreateClipResponse interface.
 */
export function instanceOfCreateClipResponse(value: object): value is CreateClipResponse {
    if (!('signature' in value) || value['signature'] === undefined) return false;
    if (!('expiration' in value) || value['expiration'] === undefined) return false;
    if (!('libraryId' in value) || value['libraryId'] === undefined) return false;
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    return true;
}

export function CreateClipResponseFromJSON(json: any): CreateClipResponse {
    return CreateClipResponseFromJSONTyped(json, false);
}

export function CreateClipResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateClipResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'signature': json['signature'],
        'expiration': json['expiration'],
        'libraryId': json['library_id'],
        'videoId': json['video_id'],
        'collectionId': json['collection_id'],
    };
}

export function CreateClipResponseToJSON(json: any): CreateClipResponse {
    return CreateClipResponseToJSONTyped(json, false);
}

export function CreateClipResponseToJSONTyped(value?: CreateClipResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signature': value['signature'],
        'expiration': value['expiration'],
        'library_id': value['libraryId'],
        'video_id': value['videoId'],
        'collection_id': value['collectionId'],
    };
}

