/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Clips | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaylistClip } from './PlaylistClip';
import {
    PlaylistClipFromJSON,
    PlaylistClipFromJSONTyped,
    PlaylistClipToJSON,
    PlaylistClipToJSONTyped,
} from './PlaylistClip';
import type { PlaylistCollaborator } from './PlaylistCollaborator';
import {
    PlaylistCollaboratorFromJSON,
    PlaylistCollaboratorFromJSONTyped,
    PlaylistCollaboratorToJSON,
    PlaylistCollaboratorToJSONTyped,
} from './PlaylistCollaborator';

/**
 * 
 * @export
 * @interface PlaylistWithDetails
 */
export interface PlaylistWithDetails {
    /**
     * 
     * @type {string}
     * @memberof PlaylistWithDetails
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistWithDetails
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistWithDetails
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaylistWithDetails
     */
    creatorUserId: string;
    /**
     * 
     * @type {Date}
     * @memberof PlaylistWithDetails
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlaylistWithDetails
     */
    updatedAt: Date;
    /**
     * 
     * @type {Array<PlaylistCollaborator>}
     * @memberof PlaylistWithDetails
     */
    collaborators: Array<PlaylistCollaborator>;
    /**
     * 
     * @type {Array<PlaylistClip>}
     * @memberof PlaylistWithDetails
     */
    clips: Array<PlaylistClip>;
}

/**
 * Check if a given object implements the PlaylistWithDetails interface.
 */
export function instanceOfPlaylistWithDetails(value: object): value is PlaylistWithDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('creatorUserId' in value) || value['creatorUserId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('collaborators' in value) || value['collaborators'] === undefined) return false;
    if (!('clips' in value) || value['clips'] === undefined) return false;
    return true;
}

export function PlaylistWithDetailsFromJSON(json: any): PlaylistWithDetails {
    return PlaylistWithDetailsFromJSONTyped(json, false);
}

export function PlaylistWithDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaylistWithDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'creatorUserId': json['creator_user_id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'collaborators': ((json['collaborators'] as Array<any>).map(PlaylistCollaboratorFromJSON)),
        'clips': ((json['clips'] as Array<any>).map(PlaylistClipFromJSON)),
    };
}

export function PlaylistWithDetailsToJSON(json: any): PlaylistWithDetails {
    return PlaylistWithDetailsToJSONTyped(json, false);
}

export function PlaylistWithDetailsToJSONTyped(value?: PlaylistWithDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'creator_user_id': value['creatorUserId'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'collaborators': ((value['collaborators'] as Array<any>).map(PlaylistCollaboratorToJSON)),
        'clips': ((value['clips'] as Array<any>).map(PlaylistClipToJSON)),
    };
}

