/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus.Clips | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { VideoDetectionRequest } from "../models/index";
import {
  VideoDetectionRequestFromJSON,
  VideoDetectionRequestToJSON,
} from "../models/index";

export interface QueueDetectionRequest {
  videoDetectionRequest: VideoDetectionRequest;
}

/**
 *
 */
export class ApexDetectionEndpointsApi extends runtime.BaseAPI {
  /**
   */
  async queueAllUnprocessedItemsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/apexdetection/enqueue-all`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async queueAllUnprocessedItems(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.queueAllUnprocessedItemsRaw(initOverrides);
  }

  /**
   */
  async queueDetectionRaw(
    requestParameters: QueueDetectionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["videoDetectionRequest"] == null) {
      throw new runtime.RequiredError(
        "videoDetectionRequest",
        'Required parameter "videoDetectionRequest" was null or undefined when calling queueDetection().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/apexdetection/enqueue`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: VideoDetectionRequestToJSON(
          requestParameters["videoDetectionRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async queueDetection(
    requestParameters: QueueDetectionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.queueDetectionRaw(requestParameters, initOverrides);
  }
}
