/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { DevLoginRequest, DevLoginResponse } from "../models/index";
import {
  DevLoginRequestFromJSON,
  DevLoginRequestToJSON,
  DevLoginResponseFromJSON,
  DevLoginResponseToJSON,
} from "../models/index";

export interface DevLoginOperationRequest {
  devLoginRequest: DevLoginRequest;
}

export interface LinkIdentityRequest {
  provider: string;
  returnUrl?: string;
}

export interface LoginRequest {
  provider: string;
  returnUrl?: string;
}

export interface PostLoginRedirectRequest {
  returnUrl?: string;
}

/**
 *
 */
export class AuthEndpointsApi extends runtime.BaseAPI {
  /**
   */
  async devLoginRaw(
    requestParameters: DevLoginOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DevLoginResponse>> {
    if (requestParameters["devLoginRequest"] == null) {
      throw new runtime.RequiredError(
        "devLoginRequest",
        'Required parameter "devLoginRequest" was null or undefined when calling devLogin().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/auth/dev-login`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: DevLoginRequestToJSON(requestParameters["devLoginRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DevLoginResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async devLogin(
    requestParameters: DevLoginOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DevLoginResponse> {
    const response = await this.devLoginRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async linkIdentityRaw(
    requestParameters: LinkIdentityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["provider"] == null) {
      throw new runtime.RequiredError(
        "provider",
        'Required parameter "provider" was null or undefined when calling linkIdentity().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["returnUrl"] != null) {
      queryParameters["returnUrl"] = requestParameters["returnUrl"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/auth/{provider}/link`;
    urlPath = urlPath.replace(
      `{${"provider"}}`,
      encodeURIComponent(String(requestParameters["provider"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async linkIdentity(
    requestParameters: LinkIdentityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.linkIdentityRaw(requestParameters, initOverrides);
  }

  /**
   */
  async loginRaw(
    requestParameters: LoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["provider"] == null) {
      throw new runtime.RequiredError(
        "provider",
        'Required parameter "provider" was null or undefined when calling login().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["returnUrl"] != null) {
      queryParameters["returnUrl"] = requestParameters["returnUrl"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/auth/{provider}/login`;
    urlPath = urlPath.replace(
      `{${"provider"}}`,
      encodeURIComponent(String(requestParameters["provider"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async login(
    requestParameters: LoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.loginRaw(requestParameters, initOverrides);
  }

  /**
   */
  async postLoginRedirectRaw(
    requestParameters: PostLoginRedirectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    if (requestParameters["returnUrl"] != null) {
      queryParameters["returnUrl"] = requestParameters["returnUrl"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/auth/post-login-redirect`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async postLoginRedirect(
    requestParameters: PostLoginRedirectRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.postLoginRedirectRaw(requestParameters, initOverrides);
  }
}
