/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  BackfillClipSummaryRequest,
  ClipSummaryBackfillResponse,
  ClipSummaryRun,
  ClipSummaryUsage,
  QueueClipSummaryRunRequest,
} from "../models/index";
import {
  BackfillClipSummaryRequestFromJSON,
  BackfillClipSummaryRequestToJSON,
  ClipSummaryBackfillResponseFromJSON,
  ClipSummaryBackfillResponseToJSON,
  ClipSummaryRunFromJSON,
  ClipSummaryRunToJSON,
  ClipSummaryUsageFromJSON,
  ClipSummaryUsageToJSON,
  QueueClipSummaryRunRequestFromJSON,
  QueueClipSummaryRunRequestToJSON,
} from "../models/index";

export interface BackfillClipSummaryOperationRequest {
  backfillClipSummaryRequest: BackfillClipSummaryRequest;
}

export interface GetClipSummaryRunsRequest {
  clipId: string;
}

export interface QueueClipSummaryRunOperationRequest {
  clipId: string;
  queueClipSummaryRunRequest: QueueClipSummaryRunRequest;
}

/**
 *
 */
export class ClipSummaryEndpointsApi extends runtime.BaseAPI {
  /**
   */
  async backfillClipSummaryRaw(
    requestParameters: BackfillClipSummaryOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ClipSummaryBackfillResponse>> {
    if (requestParameters["backfillClipSummaryRequest"] == null) {
      throw new runtime.RequiredError(
        "backfillClipSummaryRequest",
        'Required parameter "backfillClipSummaryRequest" was null or undefined when calling backfillClipSummary().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clip-summary/backfill`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: BackfillClipSummaryRequestToJSON(
          requestParameters["backfillClipSummaryRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClipSummaryBackfillResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async backfillClipSummary(
    requestParameters: BackfillClipSummaryOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ClipSummaryBackfillResponse> {
    const response = await this.backfillClipSummaryRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getClipSummaryRunsRaw(
    requestParameters: GetClipSummaryRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ClipSummaryRun>>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling getClipSummaryRuns().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clip-summary/clips/{clipId}/runs`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ClipSummaryRunFromJSON),
    );
  }

  /**
   */
  async getClipSummaryRuns(
    requestParameters: GetClipSummaryRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ClipSummaryRun>> {
    const response = await this.getClipSummaryRunsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getClipSummaryUsageRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ClipSummaryUsage>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clip-summary/usage`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ClipSummaryUsageFromJSON),
    );
  }

  /**
   */
  async getClipSummaryUsage(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ClipSummaryUsage>> {
    const response = await this.getClipSummaryUsageRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async queueClipSummaryRunRaw(
    requestParameters: QueueClipSummaryRunOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ClipSummaryRun>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling queueClipSummaryRun().',
      );
    }

    if (requestParameters["queueClipSummaryRunRequest"] == null) {
      throw new runtime.RequiredError(
        "queueClipSummaryRunRequest",
        'Required parameter "queueClipSummaryRunRequest" was null or undefined when calling queueClipSummaryRun().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clip-summary/clips/{clipId}/runs`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: QueueClipSummaryRunRequestToJSON(
          requestParameters["queueClipSummaryRunRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClipSummaryRunFromJSON(jsonValue),
    );
  }

  /**
   */
  async queueClipSummaryRun(
    requestParameters: QueueClipSummaryRunOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ClipSummaryRun> {
    const response = await this.queueClipSummaryRunRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
