/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  ClipTranscriptionBackfillResponse,
  ClipTranscriptionReviewClip,
  ClipTranscriptionRun,
  ClipTranscriptionUsage,
  QueueClipTranscriptionRunRequest,
} from "../models/index";
import {
  ClipTranscriptionBackfillResponseFromJSON,
  ClipTranscriptionBackfillResponseToJSON,
  ClipTranscriptionReviewClipFromJSON,
  ClipTranscriptionReviewClipToJSON,
  ClipTranscriptionRunFromJSON,
  ClipTranscriptionRunToJSON,
  ClipTranscriptionUsageFromJSON,
  ClipTranscriptionUsageToJSON,
  QueueClipTranscriptionRunRequestFromJSON,
  QueueClipTranscriptionRunRequestToJSON,
} from "../models/index";

export interface GetClipTranscriptionRunsRequest {
  clipId: string;
}

export interface QueueClipTranscriptionRunOperationRequest {
  clipId: string;
  queueClipTranscriptionRunRequest: QueueClipTranscriptionRunRequest;
}

/**
 *
 */
export class ClipTranscriptionEndpointsApi extends runtime.BaseAPI {
  /**
   */
  async backfillClipTranscriptionRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ClipTranscriptionBackfillResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clip-transcription/backfill`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClipTranscriptionBackfillResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async backfillClipTranscription(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ClipTranscriptionBackfillResponse> {
    const response = await this.backfillClipTranscriptionRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getClipTranscriptionReviewClipsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ClipTranscriptionReviewClip>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clip-transcription/clips`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ClipTranscriptionReviewClipFromJSON),
    );
  }

  /**
   */
  async getClipTranscriptionReviewClips(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ClipTranscriptionReviewClip>> {
    const response =
      await this.getClipTranscriptionReviewClipsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getClipTranscriptionRunsRaw(
    requestParameters: GetClipTranscriptionRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ClipTranscriptionRun>>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling getClipTranscriptionRuns().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clip-transcription/clips/{clipId}/runs`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ClipTranscriptionRunFromJSON),
    );
  }

  /**
   */
  async getClipTranscriptionRuns(
    requestParameters: GetClipTranscriptionRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ClipTranscriptionRun>> {
    const response = await this.getClipTranscriptionRunsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getClipTranscriptionUsageRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ClipTranscriptionUsage>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/clip-transcription/usage`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ClipTranscriptionUsageFromJSON),
    );
  }

  /**
   */
  async getClipTranscriptionUsage(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ClipTranscriptionUsage>> {
    const response = await this.getClipTranscriptionUsageRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async queueClipTranscriptionRunRaw(
    requestParameters: QueueClipTranscriptionRunOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ClipTranscriptionRun>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling queueClipTranscriptionRun().',
      );
    }

    if (requestParameters["queueClipTranscriptionRunRequest"] == null) {
      throw new runtime.RequiredError(
        "queueClipTranscriptionRunRequest",
        'Required parameter "queueClipTranscriptionRunRequest" was null or undefined when calling queueClipTranscriptionRun().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/clip-transcription/clips/{clipId}/runs`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: QueueClipTranscriptionRunRequestToJSON(
          requestParameters["queueClipTranscriptionRunRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClipTranscriptionRunFromJSON(jsonValue),
    );
  }

  /**
   */
  async queueClipTranscriptionRun(
    requestParameters: QueueClipTranscriptionRunOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ClipTranscriptionRun> {
    const response = await this.queueClipTranscriptionRunRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
