/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  LegendDetectionBackfillResponse,
  LegendDetectionRun,
  QueueLegendDetectionRunRequest,
} from "../models/index";
import {
  LegendDetectionBackfillResponseFromJSON,
  LegendDetectionBackfillResponseToJSON,
  LegendDetectionRunFromJSON,
  LegendDetectionRunToJSON,
  QueueLegendDetectionRunRequestFromJSON,
  QueueLegendDetectionRunRequestToJSON,
} from "../models/index";

export interface GetLegendDetectionRunsRequest {
  clipId: string;
}

export interface QueueLegendDetectionRunOperationRequest {
  clipId: string;
  queueLegendDetectionRunRequest: QueueLegendDetectionRunRequest;
}

/**
 *
 */
export class LegendDetectionEndpointsApi extends runtime.BaseAPI {
  /**
   */
  async backfillLegendDetectionRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LegendDetectionBackfillResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/legend-detection/backfill`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LegendDetectionBackfillResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async backfillLegendDetection(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LegendDetectionBackfillResponse> {
    const response = await this.backfillLegendDetectionRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getLegendDetectionRunsRaw(
    requestParameters: GetLegendDetectionRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LegendDetectionRun>>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling getLegendDetectionRuns().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/legend-detection/clips/{clipId}/runs`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(LegendDetectionRunFromJSON),
    );
  }

  /**
   */
  async getLegendDetectionRuns(
    requestParameters: GetLegendDetectionRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LegendDetectionRun>> {
    const response = await this.getLegendDetectionRunsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async queueLegendDetectionRunRaw(
    requestParameters: QueueLegendDetectionRunOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LegendDetectionRun>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling queueLegendDetectionRun().',
      );
    }

    if (requestParameters["queueLegendDetectionRunRequest"] == null) {
      throw new runtime.RequiredError(
        "queueLegendDetectionRunRequest",
        'Required parameter "queueLegendDetectionRunRequest" was null or undefined when calling queueLegendDetectionRun().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/legend-detection/clips/{clipId}/runs`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: QueueLegendDetectionRunRequestToJSON(
          requestParameters["queueLegendDetectionRunRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LegendDetectionRunFromJSON(jsonValue),
    );
  }

  /**
   */
  async queueLegendDetectionRun(
    requestParameters: QueueLegendDetectionRunOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LegendDetectionRun> {
    const response = await this.queueLegendDetectionRunRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
