/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  BackfillLegendDetectionRequest,
  LegendDetectionArchiveResponse,
  LegendDetectionBackfillResponse,
  LegendDetectionReviewClip,
  LegendDetectionRun,
  LegendDetectionUsage,
  QueueLegendDetectionRunRequest,
  SetLegendDetectionLabelRequest,
} from "../models/index";
import {
  BackfillLegendDetectionRequestFromJSON,
  BackfillLegendDetectionRequestToJSON,
  LegendDetectionArchiveResponseFromJSON,
  LegendDetectionArchiveResponseToJSON,
  LegendDetectionBackfillResponseFromJSON,
  LegendDetectionBackfillResponseToJSON,
  LegendDetectionReviewClipFromJSON,
  LegendDetectionReviewClipToJSON,
  LegendDetectionRunFromJSON,
  LegendDetectionRunToJSON,
  LegendDetectionUsageFromJSON,
  LegendDetectionUsageToJSON,
  QueueLegendDetectionRunRequestFromJSON,
  QueueLegendDetectionRunRequestToJSON,
  SetLegendDetectionLabelRequestFromJSON,
  SetLegendDetectionLabelRequestToJSON,
} from "../models/index";

export interface BackfillLegendDetectionOperationRequest {
  backfillLegendDetectionRequest: BackfillLegendDetectionRequest;
}

export interface DeleteLegendDetectionLabelRequest {
  clipId: string;
}

export interface GetLegendDetectionRunsRequest {
  clipId: string;
}

export interface QueueLegendDetectionRunOperationRequest {
  clipId: string;
  queueLegendDetectionRunRequest: QueueLegendDetectionRunRequest;
}

export interface SetLegendDetectionLabelOperationRequest {
  clipId: string;
  setLegendDetectionLabelRequest: SetLegendDetectionLabelRequest;
}

/**
 *
 */
export class LegendDetectionEndpointsApi extends runtime.BaseAPI {
  /**
   */
  async archiveLegendDetectionRunsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LegendDetectionArchiveResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/legend-detection/archive`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LegendDetectionArchiveResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async archiveLegendDetectionRuns(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LegendDetectionArchiveResponse> {
    const response = await this.archiveLegendDetectionRunsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async backfillLegendDetectionRaw(
    requestParameters: BackfillLegendDetectionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LegendDetectionBackfillResponse>> {
    if (requestParameters["backfillLegendDetectionRequest"] == null) {
      throw new runtime.RequiredError(
        "backfillLegendDetectionRequest",
        'Required parameter "backfillLegendDetectionRequest" was null or undefined when calling backfillLegendDetection().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/legend-detection/backfill`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: BackfillLegendDetectionRequestToJSON(
          requestParameters["backfillLegendDetectionRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LegendDetectionBackfillResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async backfillLegendDetection(
    requestParameters: BackfillLegendDetectionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LegendDetectionBackfillResponse> {
    const response = await this.backfillLegendDetectionRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async deleteLegendDetectionLabelRaw(
    requestParameters: DeleteLegendDetectionLabelRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling deleteLegendDetectionLabel().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/legend-detection/clips/{clipId}/label`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteLegendDetectionLabel(
    requestParameters: DeleteLegendDetectionLabelRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteLegendDetectionLabelRaw(requestParameters, initOverrides);
  }

  /**
   */
  async getLegendDetectionLegendsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/legend-detection/legends`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async getLegendDetectionLegends(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.getLegendDetectionLegendsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getLegendDetectionReasoningEffortsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/legend-detection/reasoning-efforts`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async getLegendDetectionReasoningEfforts(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response =
      await this.getLegendDetectionReasoningEffortsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getLegendDetectionReviewClipsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LegendDetectionReviewClip>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/legend-detection/clips`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(LegendDetectionReviewClipFromJSON),
    );
  }

  /**
   */
  async getLegendDetectionReviewClips(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LegendDetectionReviewClip>> {
    const response = await this.getLegendDetectionReviewClipsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getLegendDetectionRunsRaw(
    requestParameters: GetLegendDetectionRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LegendDetectionRun>>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling getLegendDetectionRuns().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/legend-detection/clips/{clipId}/runs`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(LegendDetectionRunFromJSON),
    );
  }

  /**
   */
  async getLegendDetectionRuns(
    requestParameters: GetLegendDetectionRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LegendDetectionRun>> {
    const response = await this.getLegendDetectionRunsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getLegendDetectionUsageRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LegendDetectionUsage>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/legend-detection/usage`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(LegendDetectionUsageFromJSON),
    );
  }

  /**
   */
  async getLegendDetectionUsage(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LegendDetectionUsage>> {
    const response = await this.getLegendDetectionUsageRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async queueLegendDetectionRunRaw(
    requestParameters: QueueLegendDetectionRunOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LegendDetectionRun>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling queueLegendDetectionRun().',
      );
    }

    if (requestParameters["queueLegendDetectionRunRequest"] == null) {
      throw new runtime.RequiredError(
        "queueLegendDetectionRunRequest",
        'Required parameter "queueLegendDetectionRunRequest" was null or undefined when calling queueLegendDetectionRun().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/legend-detection/clips/{clipId}/runs`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: QueueLegendDetectionRunRequestToJSON(
          requestParameters["queueLegendDetectionRunRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LegendDetectionRunFromJSON(jsonValue),
    );
  }

  /**
   */
  async queueLegendDetectionRun(
    requestParameters: QueueLegendDetectionRunOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LegendDetectionRun> {
    const response = await this.queueLegendDetectionRunRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async setLegendDetectionLabelRaw(
    requestParameters: SetLegendDetectionLabelOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["clipId"] == null) {
      throw new runtime.RequiredError(
        "clipId",
        'Required parameter "clipId" was null or undefined when calling setLegendDetectionLabel().',
      );
    }

    if (requestParameters["setLegendDetectionLabelRequest"] == null) {
      throw new runtime.RequiredError(
        "setLegendDetectionLabelRequest",
        'Required parameter "setLegendDetectionLabelRequest" was null or undefined when calling setLegendDetectionLabel().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/legend-detection/clips/{clipId}/label`;
    urlPath = urlPath.replace(
      `{${"clipId"}}`,
      encodeURIComponent(String(requestParameters["clipId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: SetLegendDetectionLabelRequestToJSON(
          requestParameters["setLegendDetectionLabelRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async setLegendDetectionLabel(
    requestParameters: SetLegendDetectionLabelOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.setLegendDetectionLabelRaw(requestParameters, initOverrides);
  }
}
