/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  ImportTwitchClipRequest,
  ImportedTwitchClipResponse,
  TwitchClipsResponse,
} from "../models/index";
import {
  ImportTwitchClipRequestFromJSON,
  ImportTwitchClipRequestToJSON,
  ImportedTwitchClipResponseFromJSON,
  ImportedTwitchClipResponseToJSON,
  TwitchClipsResponseFromJSON,
  TwitchClipsResponseToJSON,
} from "../models/index";

export interface GetTwitchClipsRequest {
  cursor?: string;
  days?: number;
  first?: number;
}

export interface ImportTwitchClipOperationRequest {
  importTwitchClipRequest: ImportTwitchClipRequest;
}

/**
 *
 */
export class TwitchClipsEndpointsApi extends runtime.BaseAPI {
  /**
   */
  async getTwitchClipsRaw(
    requestParameters: GetTwitchClipsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TwitchClipsResponse>> {
    const queryParameters: any = {};

    if (requestParameters["cursor"] != null) {
      queryParameters["cursor"] = requestParameters["cursor"];
    }

    if (requestParameters["days"] != null) {
      queryParameters["days"] = requestParameters["days"];
    }

    if (requestParameters["first"] != null) {
      queryParameters["first"] = requestParameters["first"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/twitch/clips`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TwitchClipsResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async getTwitchClips(
    requestParameters: GetTwitchClipsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TwitchClipsResponse> {
    const response = await this.getTwitchClipsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async importTwitchClipRaw(
    requestParameters: ImportTwitchClipOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ImportedTwitchClipResponse>> {
    if (requestParameters["importTwitchClipRequest"] == null) {
      throw new runtime.RequiredError(
        "importTwitchClipRequest",
        'Required parameter "importTwitchClipRequest" was null or undefined when calling importTwitchClip().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/api/twitch/clips/import`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: ImportTwitchClipRequestToJSON(
          requestParameters["importTwitchClipRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ImportedTwitchClipResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async importTwitchClip(
    requestParameters: ImportTwitchClipOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ImportedTwitchClipResponse> {
    const response = await this.importTwitchClipRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
