/* tslint:disable */
/* eslint-disable */
/**
 * Reelshelf | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  LinkedIdentity,
  StorageUsageResponse,
  UserProfile,
} from "../models/index";
import {
  LinkedIdentityFromJSON,
  LinkedIdentityToJSON,
  StorageUsageResponseFromJSON,
  StorageUsageResponseToJSON,
  UserProfileFromJSON,
  UserProfileToJSON,
} from "../models/index";

export interface ApiUserUserIdGetRequest {
  userId: string;
}

export interface UnlinkMyIdentityRequest {
  provider: string;
}

/**
 *
 */
export class UserEndpointsApi extends runtime.BaseAPI {
  /**
   */
  async apiMeGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UserProfile>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/me`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserProfileFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiMeGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UserProfile> {
    const response = await this.apiMeGetRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async apiUserUserIdGetRaw(
    requestParameters: ApiUserUserIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UserProfile>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling apiUserUserIdGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/user/{userId}`;
    urlPath = urlPath.replace(
      `{${"userId"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserProfileFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiUserUserIdGet(
    requestParameters: ApiUserUserIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UserProfile> {
    const response = await this.apiUserUserIdGetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async apiUsersSuggestionsGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<UserProfile>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/users/suggestions`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(UserProfileFromJSON),
    );
  }

  /**
   */
  async apiUsersSuggestionsGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<UserProfile>> {
    const response = await this.apiUsersSuggestionsGetRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getMyLinkedIdentitiesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<LinkedIdentity>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/me/identities`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(LinkedIdentityFromJSON),
    );
  }

  /**
   */
  async getMyLinkedIdentities(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<LinkedIdentity>> {
    const response = await this.getMyLinkedIdentitiesRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getMyStorageUsageRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StorageUsageResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/me/storage`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      StorageUsageResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async getMyStorageUsage(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StorageUsageResponse> {
    const response = await this.getMyStorageUsageRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async unlinkMyIdentityRaw(
    requestParameters: UnlinkMyIdentityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["provider"] == null) {
      throw new runtime.RequiredError(
        "provider",
        'Required parameter "provider" was null or undefined when calling unlinkMyIdentity().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/me/identities/{provider}`;
    urlPath = urlPath.replace(
      `{${"provider"}}`,
      encodeURIComponent(String(requestParameters["provider"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async unlinkMyIdentity(
    requestParameters: UnlinkMyIdentityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.unlinkMyIdentityRaw(requestParameters, initOverrides);
  }
}
