/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  VideoProgressUpdate,
} from '../models/index';
import {
    VideoProgressUpdateFromJSON,
    VideoProgressUpdateToJSON,
} from '../models/index';

export interface ReceiveVideoProgressRequest {
    videoProgressUpdate: VideoProgressUpdate;
}

/**
 * 
 */
export class BunnyWebhookEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async receiveVideoProgressRaw(requestParameters: ReceiveVideoProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['videoProgressUpdate'] == null) {
            throw new runtime.RequiredError(
                'videoProgressUpdate',
                'Required parameter "videoProgressUpdate" was null or undefined when calling receiveVideoProgress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/webhooks/bunny/video-progress`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoProgressUpdateToJSON(requestParameters['videoProgressUpdate']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async receiveVideoProgress(requestParameters: ReceiveVideoProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.receiveVideoProgressRaw(requestParameters, initOverrides);
    }

    /**
     */
    async testWebhookRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/webhooks/bunny/test`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async testWebhook(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.testWebhookRaw(initOverrides);
    }

}
