/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DiscordUser,
} from '../models/index';
import {
    DiscordUserFromJSON,
    DiscordUserToJSON,
} from '../models/index';

export interface UserUserIdGetRequest {
    userId: string;
}

/**
 * 
 */
export class DiscordUserEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async meGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DiscordUser>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DiscordUserFromJSON(jsonValue));
    }

    /**
     */
    async meGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DiscordUser> {
        const response = await this.meGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async userUserIdGetRaw(requestParameters: UserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DiscordUser>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling userUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DiscordUserFromJSON(jsonValue));
    }

    /**
     */
    async userUserIdGet(requestParameters: UserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DiscordUser> {
        const response = await this.userUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
