/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LinkRequest,
  UserFrequentLink,
} from '../models/index';
import {
    LinkRequestFromJSON,
    LinkRequestToJSON,
    UserFrequentLinkFromJSON,
    UserFrequentLinkToJSON,
} from '../models/index';

export interface AddLinkRequest {
    linkRequest: LinkRequest;
}

export interface DeleteLinkRequest {
    id: string;
}

/**
 * 
 */
export class LinksEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async addLinkRaw(requestParameters: AddLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['linkRequest'] == null) {
            throw new runtime.RequiredError(
                'linkRequest',
                'Required parameter "linkRequest" was null or undefined when calling addLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/links`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LinkRequestToJSON(requestParameters['linkRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async addLink(requestParameters: AddLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addLinkRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteLinkRaw(requestParameters: DeleteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/links/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteLink(requestParameters: DeleteLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLinkRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getLinksForUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserFrequentLink>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/links`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserFrequentLinkFromJSON));
    }

    /**
     */
    async getLinksForUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserFrequentLink>> {
        const response = await this.getLinksForUserRaw(initOverrides);
        return await response.value();
    }

}
