/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CurrentMapRotation,
} from '../models/index';
import {
    CurrentMapRotationFromJSON,
    CurrentMapRotationToJSON,
} from '../models/index';

/**
 * 
 */
export class NucleusApi extends runtime.BaseAPI {

    /**
     */
    async getApexMapRotationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentMapRotation>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/apex-legends/map-rotation`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentMapRotationFromJSON(jsonValue));
    }

    /**
     */
    async getApexMapRotation(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentMapRotation> {
        const response = await this.getApexMapRotationRaw(initOverrides);
        return await response.value();
    }

}
