/* tslint:disable */
/* eslint-disable */
/**
 * Nucleus | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddClipToPlaylistRequest,
  AddCollaboratorRequest,
  CreatePlaylistRequest,
  Playlist,
  PlaylistCollaborator,
  PlaylistSummary,
  PlaylistWithDetails,
  ReorderPlaylistClipsRequest,
  UpdatePlaylistRequest,
} from '../models/index';
import {
    AddClipToPlaylistRequestFromJSON,
    AddClipToPlaylistRequestToJSON,
    AddCollaboratorRequestFromJSON,
    AddCollaboratorRequestToJSON,
    CreatePlaylistRequestFromJSON,
    CreatePlaylistRequestToJSON,
    PlaylistFromJSON,
    PlaylistToJSON,
    PlaylistCollaboratorFromJSON,
    PlaylistCollaboratorToJSON,
    PlaylistSummaryFromJSON,
    PlaylistSummaryToJSON,
    PlaylistWithDetailsFromJSON,
    PlaylistWithDetailsToJSON,
    ReorderPlaylistClipsRequestFromJSON,
    ReorderPlaylistClipsRequestToJSON,
    UpdatePlaylistRequestFromJSON,
    UpdatePlaylistRequestToJSON,
} from '../models/index';

export interface AddClipsToPlaylistRequest {
    id: string;
    addClipToPlaylistRequest: AddClipToPlaylistRequest;
}

export interface AddCollaboratorOperationRequest {
    id: string;
    addCollaboratorRequest: AddCollaboratorRequest;
}

export interface CreatePlaylistOperationRequest {
    createPlaylistRequest: CreatePlaylistRequest;
}

export interface DeletePlaylistRequest {
    id: string;
}

export interface GetCollaboratorsRequest {
    id: string;
}

export interface GetPlaylistByIdRequest {
    id: string;
}

export interface RemoveClipFromPlaylistRequest {
    id: string;
    clipId: string;
}

export interface RemoveCollaboratorRequest {
    id: string;
    userId: string;
}

export interface ReorderPlaylistClipsOperationRequest {
    id: string;
    reorderPlaylistClipsRequest: ReorderPlaylistClipsRequest;
}

export interface UpdatePlaylistOperationRequest {
    id: string;
    updatePlaylistRequest: UpdatePlaylistRequest;
}

/**
 * 
 */
export class PlaylistEndpointsApi extends runtime.BaseAPI {

    /**
     */
    async addClipsToPlaylistRaw(requestParameters: AddClipsToPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistWithDetails>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addClipsToPlaylist().'
            );
        }

        if (requestParameters['addClipToPlaylistRequest'] == null) {
            throw new runtime.RequiredError(
                'addClipToPlaylistRequest',
                'Required parameter "addClipToPlaylistRequest" was null or undefined when calling addClipsToPlaylist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/playlists/{id}/clips`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddClipToPlaylistRequestToJSON(requestParameters['addClipToPlaylistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistWithDetailsFromJSON(jsonValue));
    }

    /**
     */
    async addClipsToPlaylist(requestParameters: AddClipsToPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistWithDetails> {
        const response = await this.addClipsToPlaylistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async addCollaboratorRaw(requestParameters: AddCollaboratorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlaylistCollaborator>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addCollaborator().'
            );
        }

        if (requestParameters['addCollaboratorRequest'] == null) {
            throw new runtime.RequiredError(
                'addCollaboratorRequest',
                'Required parameter "addCollaboratorRequest" was null or undefined when calling addCollaborator().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/playlists/{id}/collaborators`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddCollaboratorRequestToJSON(requestParameters['addCollaboratorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlaylistCollaboratorFromJSON));
    }

    /**
     */
    async addCollaborator(requestParameters: AddCollaboratorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlaylistCollaborator>> {
        const response = await this.addCollaboratorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createPlaylistRaw(requestParameters: CreatePlaylistOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Playlist>> {
        if (requestParameters['createPlaylistRequest'] == null) {
            throw new runtime.RequiredError(
                'createPlaylistRequest',
                'Required parameter "createPlaylistRequest" was null or undefined when calling createPlaylist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/playlists`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePlaylistRequestToJSON(requestParameters['createPlaylistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistFromJSON(jsonValue));
    }

    /**
     */
    async createPlaylist(requestParameters: CreatePlaylistOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Playlist> {
        const response = await this.createPlaylistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deletePlaylistRaw(requestParameters: DeletePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePlaylist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/playlists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deletePlaylist(requestParameters: DeletePlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePlaylistRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getCollaboratorsRaw(requestParameters: GetCollaboratorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlaylistCollaborator>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCollaborators().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/playlists/{id}/collaborators`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlaylistCollaboratorFromJSON));
    }

    /**
     */
    async getCollaborators(requestParameters: GetCollaboratorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlaylistCollaborator>> {
        const response = await this.getCollaboratorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPlaylistByIdRaw(requestParameters: GetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistWithDetails>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPlaylistById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/playlists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistWithDetailsFromJSON(jsonValue));
    }

    /**
     */
    async getPlaylistById(requestParameters: GetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistWithDetails> {
        const response = await this.getPlaylistByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPlaylistsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlaylistSummary>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/playlists`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlaylistSummaryFromJSON));
    }

    /**
     */
    async getPlaylists(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlaylistSummary>> {
        const response = await this.getPlaylistsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async removeClipFromPlaylistRaw(requestParameters: RemoveClipFromPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeClipFromPlaylist().'
            );
        }

        if (requestParameters['clipId'] == null) {
            throw new runtime.RequiredError(
                'clipId',
                'Required parameter "clipId" was null or undefined when calling removeClipFromPlaylist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/playlists/{id}/clips/{clipId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"clipId"}}`, encodeURIComponent(String(requestParameters['clipId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async removeClipFromPlaylist(requestParameters: RemoveClipFromPlaylistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeClipFromPlaylistRaw(requestParameters, initOverrides);
    }

    /**
     */
    async removeCollaboratorRaw(requestParameters: RemoveCollaboratorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeCollaborator().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeCollaborator().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/playlists/{id}/collaborators/{userId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async removeCollaborator(requestParameters: RemoveCollaboratorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeCollaboratorRaw(requestParameters, initOverrides);
    }

    /**
     */
    async reorderPlaylistClipsRaw(requestParameters: ReorderPlaylistClipsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistWithDetails>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reorderPlaylistClips().'
            );
        }

        if (requestParameters['reorderPlaylistClipsRequest'] == null) {
            throw new runtime.RequiredError(
                'reorderPlaylistClipsRequest',
                'Required parameter "reorderPlaylistClipsRequest" was null or undefined when calling reorderPlaylistClips().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/playlists/{id}/clips/reorder`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ReorderPlaylistClipsRequestToJSON(requestParameters['reorderPlaylistClipsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistWithDetailsFromJSON(jsonValue));
    }

    /**
     */
    async reorderPlaylistClips(requestParameters: ReorderPlaylistClipsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistWithDetails> {
        const response = await this.reorderPlaylistClipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updatePlaylistRaw(requestParameters: UpdatePlaylistOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Playlist>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePlaylist().'
            );
        }

        if (requestParameters['updatePlaylistRequest'] == null) {
            throw new runtime.RequiredError(
                'updatePlaylistRequest',
                'Required parameter "updatePlaylistRequest" was null or undefined when calling updatePlaylist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/playlists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePlaylistRequestToJSON(requestParameters['updatePlaylistRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistFromJSON(jsonValue));
    }

    /**
     */
    async updatePlaylist(requestParameters: UpdatePlaylistOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Playlist> {
        const response = await this.updatePlaylistRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
