/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/_library'
import { Route as LegendDetectionRouteImport } from './routes/legend-detection'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as LibraryIndexRouteImport } from './routes/_library/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsPlaylistIdRouteImport } from './routes/collections/$playlistId'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists/$playlistId'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as GamesSlugClipIdRouteImport } from './routes/games/$slug/$clipId'
import { Route as LibraryGamesSlugIndexRouteImport } from './routes/_library/games/$slug/index'

const LibraryRoute = LibraryRouteImport.update({
  id: '/_library',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendDetectionRoute = LegendDetectionRouteImport.update({
  id: '/legend-detection',
  path: '/legend-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsPlaylistIdRoute = CollectionsPlaylistIdRouteImport.update({
  id: '/collections/$playlistId',
  path: '/collections/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugClipIdRoute = GamesSlugClipIdRouteImport.update({
  id: '/games/$slug/$clipId',
  path: '/games/$slug/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryGamesSlugIndexRoute = LibraryGamesSlugIndexRouteImport.update({
  id: '/games/$slug/',
  path: '/games/$slug/',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LibraryIndexRoute
  '/legend-detection': typeof LegendDetectionRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/upload': typeof UploadRoute
  '/collections/$playlistId': typeof CollectionsPlaylistIdRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/collections/': typeof CollectionsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/games/$slug/$clipId': typeof GamesSlugClipIdRoute
  '/games/$slug/': typeof LibraryGamesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/legend-detection': typeof LegendDetectionRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/upload': typeof UploadRoute
  '/collections/$playlistId': typeof CollectionsPlaylistIdRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof LibraryIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/games/$slug/$clipId': typeof GamesSlugClipIdRoute
  '/games/$slug': typeof LibraryGamesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_library': typeof LibraryRouteWithChildren
  '/legend-detection': typeof LegendDetectionRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/upload': typeof UploadRoute
  '/collections/$playlistId': typeof CollectionsPlaylistIdRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/_library/': typeof LibraryIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/games/$slug/$clipId': typeof GamesSlugClipIdRoute
  '/_library/games/$slug/': typeof LibraryGamesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legend-detection'
    | '/settings'
    | '/sign-in'
    | '/upload'
    | '/collections/$playlistId'
    | '/playlists/$playlistId'
    | '/share/$token'
    | '/collections/'
    | '/playlists/'
    | '/games/$slug/$clipId'
    | '/games/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/legend-detection'
    | '/settings'
    | '/sign-in'
    | '/upload'
    | '/collections/$playlistId'
    | '/playlists/$playlistId'
    | '/share/$token'
    | '/'
    | '/collections'
    | '/playlists'
    | '/games/$slug/$clipId'
    | '/games/$slug'
  id:
    | '__root__'
    | '/_library'
    | '/legend-detection'
    | '/settings'
    | '/sign-in'
    | '/upload'
    | '/collections/$playlistId'
    | '/playlists/$playlistId'
    | '/share/$token'
    | '/_library/'
    | '/collections/'
    | '/playlists/'
    | '/games/$slug/$clipId'
    | '/_library/games/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LibraryRoute: typeof LibraryRouteWithChildren
  LegendDetectionRoute: typeof LegendDetectionRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  UploadRoute: typeof UploadRoute
  CollectionsPlaylistIdRoute: typeof CollectionsPlaylistIdRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  GamesSlugClipIdRoute: typeof GamesSlugClipIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_library': {
      id: '/_library'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legend-detection': {
      id: '/legend-detection'
      path: '/legend-detection'
      fullPath: '/legend-detection'
      preLoaderRoute: typeof LegendDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/': {
      id: '/_library/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$playlistId': {
      id: '/collections/$playlistId'
      path: '/collections/$playlistId'
      fullPath: '/collections/$playlistId'
      preLoaderRoute: typeof CollectionsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug/$clipId': {
      id: '/games/$slug/$clipId'
      path: '/games/$slug/$clipId'
      fullPath: '/games/$slug/$clipId'
      preLoaderRoute: typeof GamesSlugClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/games/$slug/': {
      id: '/_library/games/$slug/'
      path: '/games/$slug'
      fullPath: '/games/$slug/'
      preLoaderRoute: typeof LibraryGamesSlugIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryGamesSlugIndexRoute: typeof LibraryGamesSlugIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryGamesSlugIndexRoute: LibraryGamesSlugIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LibraryRoute: LibraryRouteWithChildren,
  LegendDetectionRoute: LegendDetectionRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  UploadRoute: UploadRoute,
  CollectionsPlaylistIdRoute: CollectionsPlaylistIdRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  GamesSlugClipIdRoute: GamesSlugClipIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
