/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists/$playlistId'
import { Route as GamesSlugIndexRouteImport } from './routes/games/$slug/index'
import { Route as GamesSlugClipIdRouteImport } from './routes/games/$slug/$clipId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugIndexRoute = GamesSlugIndexRouteImport.update({
  id: '/games/$slug/',
  path: '/games/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugClipIdRoute = GamesSlugClipIdRouteImport.update({
  id: '/games/$slug/$clipId',
  path: '/games/$slug/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/games/$slug/$clipId': typeof GamesSlugClipIdRoute
  '/games/$slug/': typeof GamesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/games/$slug/$clipId': typeof GamesSlugClipIdRoute
  '/games/$slug': typeof GamesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/games/$slug/$clipId': typeof GamesSlugClipIdRoute
  '/games/$slug/': typeof GamesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/upload'
    | '/playlists/$playlistId'
    | '/share/$token'
    | '/playlists/'
    | '/games/$slug/$clipId'
    | '/games/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/upload'
    | '/playlists/$playlistId'
    | '/share/$token'
    | '/playlists'
    | '/games/$slug/$clipId'
    | '/games/$slug'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/upload'
    | '/playlists/$playlistId'
    | '/share/$token'
    | '/playlists/'
    | '/games/$slug/$clipId'
    | '/games/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  GamesSlugClipIdRoute: typeof GamesSlugClipIdRoute
  GamesSlugIndexRoute: typeof GamesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug/': {
      id: '/games/$slug/'
      path: '/games/$slug'
      fullPath: '/games/$slug/'
      preLoaderRoute: typeof GamesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug/$clipId': {
      id: '/games/$slug/$clipId'
      path: '/games/$slug/$clipId'
      fullPath: '/games/$slug/$clipId'
      preLoaderRoute: typeof GamesSlugClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  GamesSlugClipIdRoute: GamesSlugClipIdRoute,
  GamesSlugIndexRoute: GamesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
